//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetSteps.Integrations.Service.OrderSVC {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultDetail", Namespace="urn:EncoreOrderFulfillmentService")]
    [System.SerializableAttribute()]
    public partial class FaultDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NetSteps.Integrations.Service.OrderSVC.FaultDetail InnerFaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object OuterFaultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NetSteps.Integrations.Service.OrderSVC.FaultDetail InnerFault {
            get {
                return this.InnerFaultField;
            }
            set {
                if ((object.ReferenceEquals(this.InnerFaultField, value) != true)) {
                    this.InnerFaultField = value;
                    this.RaisePropertyChanged("InnerFault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object OuterFault {
            get {
                return this.OuterFaultField;
            }
            set {
                if ((object.ReferenceEquals(this.OuterFaultField, value) != true)) {
                    this.OuterFaultField = value;
                    this.RaisePropertyChanged("OuterFault");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://orderfulfillment.michetesting.com", ConfigurationName="OrderSVC.OrderFulfillmentService")]
    public interface OrderFulfillmentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://orderfulfillment.michetesting.com/OrderFulfillmentService/GetOrdersToFulfi" +
            "ll", ReplyAction="http://orderfulfillment.michetesting.com/OrderFulfillmentService/GetOrdersToFulfi" +
            "llResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NetSteps.Integrations.Service.OrderSVC.FaultDetail), Action="http://orderfulfillment.michetesting.com/OrderFulfillmentService/GetOrdersToFulfi" +
            "llFaultDetailFault", Name="FaultDetail", Namespace="urn:EncoreOrderFulfillmentService")]
        string GetOrdersToFulfill(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://orderfulfillment.michetesting.com/OrderFulfillmentService/SendOrderFulfill" +
            "mentAcknowledgment", ReplyAction="http://orderfulfillment.michetesting.com/OrderFulfillmentService/SendOrderFulfill" +
            "mentAcknowledgmentResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NetSteps.Integrations.Service.OrderSVC.FaultDetail), Action="http://orderfulfillment.michetesting.com/OrderFulfillmentService/SendOrderFulfill" +
            "mentAcknowledgmentFaultDetailFault", Name="FaultDetail", Namespace="urn:EncoreOrderFulfillmentService")]
        string SendOrderFulfillmentAcknowledgment(string userName, string password, string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://orderfulfillment.michetesting.com/OrderFulfillmentService/SendOrderShippin" +
            "gInformation", ReplyAction="http://orderfulfillment.michetesting.com/OrderFulfillmentService/SendOrderShippin" +
            "gInformationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NetSteps.Integrations.Service.OrderSVC.FaultDetail), Action="http://orderfulfillment.michetesting.com/OrderFulfillmentService/SendOrderShippin" +
            "gInformationFaultDetailFault", Name="FaultDetail", Namespace="urn:EncoreOrderFulfillmentService")]
        string SendOrderShippingInformation(string userName, string password, string xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderFulfillmentServiceChannel : NetSteps.Integrations.Service.OrderSVC.OrderFulfillmentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderFulfillmentServiceClient : System.ServiceModel.ClientBase<NetSteps.Integrations.Service.OrderSVC.OrderFulfillmentService>, NetSteps.Integrations.Service.OrderSVC.OrderFulfillmentService {
        
        public OrderFulfillmentServiceClient() {
        }
        
        public OrderFulfillmentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderFulfillmentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderFulfillmentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderFulfillmentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetOrdersToFulfill(string userName, string password) {
            return base.Channel.GetOrdersToFulfill(userName, password);
        }
        
        public string SendOrderFulfillmentAcknowledgment(string userName, string password, string xml) {
            return base.Channel.SendOrderFulfillmentAcknowledgment(userName, password, xml);
        }
        
        public string SendOrderShippingInformation(string userName, string password, string xml) {
            return base.Channel.SendOrderShippingInformation(userName, password, xml);
        }
    }
}
