
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;

namespace NetSteps.Data.Entities
{
    public partial class NetStepsEntities : ObjectContext
    {
        public const string ConnectionString = "name=NetStepsEntities";
        public const string ContainerName = "NetStepsEntities";
    
        #region Constructors
    
        public NetStepsEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            Initialize();
        }
    
        public NetStepsEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            Initialize();
        }
    
    
        private void Initialize()
        {
            // Creating proxies requires the use of the ProxyDataContractResolver and
            // may allow lazy loading which can expand the loaded graph during serialization.
            ContextOptions.ProxyCreationEnabled = false;
            ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
        }
    
        private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
        {
            var entity = e.Entity as IObjectWithChangeTracker;
            if (entity != null)
            {
                bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
                try
                {
                    entity.MarkAsUnchanged();
                }
                finally
                {
                    entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
                }
                this.StoreReferenceKeyValues(entity);
            }
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<AccountPhone> AccountPhones
        {
            get { return _accountPhones  ?? (_accountPhones = CreateObjectSet<AccountPhone>("AccountPhones")); }
        }
        private ObjectSet<AccountPhone> _accountPhones;
    
        public ObjectSet<AccountType> AccountTypes
        {
            get { return _accountTypes  ?? (_accountTypes = CreateObjectSet<AccountType>("AccountTypes")); }
        }
        private ObjectSet<AccountType> _accountTypes;
    
        public ObjectSet<AddressType> AddressTypes
        {
            get { return _addressTypes  ?? (_addressTypes = CreateObjectSet<AddressType>("AddressTypes")); }
        }
        private ObjectSet<AddressType> _addressTypes;
    
        public ObjectSet<Application> Applications
        {
            get { return _applications  ?? (_applications = CreateObjectSet<Application>("Applications")); }
        }
        private ObjectSet<Application> _applications;
    
        public ObjectSet<ApplicationUsageLog> ApplicationUsageLogs
        {
            get { return _applicationUsageLogs  ?? (_applicationUsageLogs = CreateObjectSet<ApplicationUsageLog>("ApplicationUsageLogs")); }
        }
        private ObjectSet<ApplicationUsageLog> _applicationUsageLogs;
    
        public ObjectSet<Archive> Archives
        {
            get { return _archives  ?? (_archives = CreateObjectSet<Archive>("Archives")); }
        }
        private ObjectSet<Archive> _archives;
    
        public ObjectSet<Country> Countries
        {
            get { return _countries  ?? (_countries = CreateObjectSet<Country>("Countries")); }
        }
        private ObjectSet<Country> _countries;
    
        public ObjectSet<Currency> Currencies
        {
            get { return _currencies  ?? (_currencies = CreateObjectSet<Currency>("Currencies")); }
        }
        private ObjectSet<Currency> _currencies;
    
        public ObjectSet<Function> Functions
        {
            get { return _functions  ?? (_functions = CreateObjectSet<Function>("Functions")); }
        }
        private ObjectSet<Function> _functions;
    
        public ObjectSet<Gender> Genders
        {
            get { return _genders  ?? (_genders = CreateObjectSet<Gender>("Genders")); }
        }
        private ObjectSet<Gender> _genders;
    
        public ObjectSet<Language> Languages
        {
            get { return _languages  ?? (_languages = CreateObjectSet<Language>("Languages")); }
        }
        private ObjectSet<Language> _languages;
    
        public ObjectSet<Market> Markets
        {
            get { return _markets  ?? (_markets = CreateObjectSet<Market>("Markets")); }
        }
        private ObjectSet<Market> _markets;
    
        public ObjectSet<OrderCustomer> OrderCustomers
        {
            get { return _orderCustomers  ?? (_orderCustomers = CreateObjectSet<OrderCustomer>("OrderCustomers")); }
        }
        private ObjectSet<OrderCustomer> _orderCustomers;
    
        public ObjectSet<OrderPayment> OrderPayments
        {
            get { return _orderPayments  ?? (_orderPayments = CreateObjectSet<OrderPayment>("OrderPayments")); }
        }
        private ObjectSet<OrderPayment> _orderPayments;
    
        public ObjectSet<OrderPaymentStatus> OrderPaymentStatuses
        {
            get { return _orderPaymentStatuses  ?? (_orderPaymentStatuses = CreateObjectSet<OrderPaymentStatus>("OrderPaymentStatuses")); }
        }
        private ObjectSet<OrderPaymentStatus> _orderPaymentStatuses;
    
        public ObjectSet<OrderStatus> OrderStatuses
        {
            get { return _orderStatuses  ?? (_orderStatuses = CreateObjectSet<OrderStatus>("OrderStatuses")); }
        }
        private ObjectSet<OrderStatus> _orderStatuses;
    
        public ObjectSet<OrderType> OrderTypes
        {
            get { return _orderTypes  ?? (_orderTypes = CreateObjectSet<OrderType>("OrderTypes")); }
        }
        private ObjectSet<OrderType> _orderTypes;
    
        public ObjectSet<PaymentType> PaymentTypes
        {
            get { return _paymentTypes  ?? (_paymentTypes = CreateObjectSet<PaymentType>("PaymentTypes")); }
        }
        private ObjectSet<PaymentType> _paymentTypes;
    
        public ObjectSet<ProductPrice> ProductPrices
        {
            get { return _productPrices  ?? (_productPrices = CreateObjectSet<ProductPrice>("ProductPrices")); }
        }
        private ObjectSet<ProductPrice> _productPrices;
    
        public ObjectSet<ProductPriceType> ProductPriceTypes
        {
            get { return _productPriceTypes  ?? (_productPriceTypes = CreateObjectSet<ProductPriceType>("ProductPriceTypes")); }
        }
        private ObjectSet<ProductPriceType> _productPriceTypes;
    
        public ObjectSet<ProductType> ProductTypes
        {
            get { return _productTypes  ?? (_productTypes = CreateObjectSet<ProductType>("ProductTypes")); }
        }
        private ObjectSet<ProductType> _productTypes;
    
        public ObjectSet<ShippingMethod> ShippingMethods
        {
            get { return _shippingMethods  ?? (_shippingMethods = CreateObjectSet<ShippingMethod>("ShippingMethods")); }
        }
        private ObjectSet<ShippingMethod> _shippingMethods;
    
        public ObjectSet<ShippingOrderType> ShippingOrderTypes
        {
            get { return _shippingOrderTypes  ?? (_shippingOrderTypes = CreateObjectSet<ShippingOrderType>("ShippingOrderTypes")); }
        }
        private ObjectSet<ShippingOrderType> _shippingOrderTypes;
    
        public ObjectSet<ShippingRateGroup> ShippingRateGroups
        {
            get { return _shippingRateGroups  ?? (_shippingRateGroups = CreateObjectSet<ShippingRateGroup>("ShippingRateGroups")); }
        }
        private ObjectSet<ShippingRateGroup> _shippingRateGroups;
    
        public ObjectSet<ShippingRate> ShippingRates
        {
            get { return _shippingRates  ?? (_shippingRates = CreateObjectSet<ShippingRate>("ShippingRates")); }
        }
        private ObjectSet<ShippingRate> _shippingRates;
    
        public ObjectSet<ShippingRegion> ShippingRegions
        {
            get { return _shippingRegions  ?? (_shippingRegions = CreateObjectSet<ShippingRegion>("ShippingRegions")); }
        }
        private ObjectSet<ShippingRegion> _shippingRegions;
    
        public ObjectSet<StateProvince> StateProvinces
        {
            get { return _stateProvinces  ?? (_stateProvinces = CreateObjectSet<StateProvince>("StateProvinces")); }
        }
        private ObjectSet<StateProvince> _stateProvinces;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;
    
        public ObjectSet<UserType> UserTypes
        {
            get { return _userTypes  ?? (_userTypes = CreateObjectSet<UserType>("UserTypes")); }
        }
        private ObjectSet<UserType> _userTypes;
    
        public ObjectSet<ApplicationRunningInstance> ApplicationRunningInstances
        {
            get { return _applicationRunningInstances  ?? (_applicationRunningInstances = CreateObjectSet<ApplicationRunningInstance>("ApplicationRunningInstances")); }
        }
        private ObjectSet<ApplicationRunningInstance> _applicationRunningInstances;
    
        public ObjectSet<MailAccount> MailAccounts
        {
            get { return _mailAccounts  ?? (_mailAccounts = CreateObjectSet<MailAccount>("MailAccounts")); }
        }
        private ObjectSet<MailAccount> _mailAccounts;
    
        public ObjectSet<AccountPaymentMethod> AccountPaymentMethods
        {
            get { return _accountPaymentMethods  ?? (_accountPaymentMethods = CreateObjectSet<AccountPaymentMethod>("AccountPaymentMethods")); }
        }
        private ObjectSet<AccountPaymentMethod> _accountPaymentMethods;
    
        public ObjectSet<AccountStatus> AccountStatuses
        {
            get { return _accountStatuses  ?? (_accountStatuses = CreateObjectSet<AccountStatus>("AccountStatuses")); }
        }
        private ObjectSet<AccountStatus> _accountStatuses;
    
        public ObjectSet<OrderItemType> OrderItemTypes
        {
            get { return _orderItemTypes  ?? (_orderItemTypes = CreateObjectSet<OrderItemType>("OrderItemTypes")); }
        }
        private ObjectSet<OrderItemType> _orderItemTypes;
    
        public ObjectSet<ArchiveType> ArchiveTypes
        {
            get { return _archiveTypes  ?? (_archiveTypes = CreateObjectSet<ArchiveType>("ArchiveTypes")); }
        }
        private ObjectSet<ArchiveType> _archiveTypes;
    
        public ObjectSet<Account> Accounts
        {
            get { return _accounts  ?? (_accounts = CreateObjectSet<Account>("Accounts")); }
        }
        private ObjectSet<Account> _accounts;
    
        public ObjectSet<PhoneType> PhoneTypes
        {
            get { return _phoneTypes  ?? (_phoneTypes = CreateObjectSet<PhoneType>("PhoneTypes")); }
        }
        private ObjectSet<PhoneType> _phoneTypes;
    
        public ObjectSet<PaymentGateway> PaymentGateways
        {
            get { return _paymentGateways  ?? (_paymentGateways = CreateObjectSet<PaymentGateway>("PaymentGateways")); }
        }
        private ObjectSet<PaymentGateway> _paymentGateways;
    
        public ObjectSet<PaymentOrderType> PaymentOrderTypes
        {
            get { return _paymentOrderTypes  ?? (_paymentOrderTypes = CreateObjectSet<PaymentOrderType>("PaymentOrderTypes")); }
        }
        private ObjectSet<PaymentOrderType> _paymentOrderTypes;
    
        public ObjectSet<OrderShipment> OrderShipments
        {
            get { return _orderShipments  ?? (_orderShipments = CreateObjectSet<OrderShipment>("OrderShipments")); }
        }
        private ObjectSet<OrderShipment> _orderShipments;
    
        public ObjectSet<ProductProperty> ProductProperties
        {
            get { return _productProperties  ?? (_productProperties = CreateObjectSet<ProductProperty>("ProductProperties")); }
        }
        private ObjectSet<ProductProperty> _productProperties;
    
        public ObjectSet<ProductPropertyTypeRelation> ProductPropertyTypeRelations
        {
            get { return _productPropertyTypeRelations  ?? (_productPropertyTypeRelations = CreateObjectSet<ProductPropertyTypeRelation>("ProductPropertyTypeRelations")); }
        }
        private ObjectSet<ProductPropertyTypeRelation> _productPropertyTypeRelations;
    
        public ObjectSet<ProductPropertyType> ProductPropertyTypes
        {
            get { return _productPropertyTypes  ?? (_productPropertyTypes = CreateObjectSet<ProductPropertyType>("ProductPropertyTypes")); }
        }
        private ObjectSet<ProductPropertyType> _productPropertyTypes;
    
        public ObjectSet<ProductPropertyValue> ProductPropertyValues
        {
            get { return _productPropertyValues  ?? (_productPropertyValues = CreateObjectSet<ProductPropertyValue>("ProductPropertyValues")); }
        }
        private ObjectSet<ProductPropertyValue> _productPropertyValues;
    
        public ObjectSet<CampaignType> CampaignTypes
        {
            get { return _campaignTypes  ?? (_campaignTypes = CreateObjectSet<CampaignType>("CampaignTypes")); }
        }
        private ObjectSet<CampaignType> _campaignTypes;
    
        public ObjectSet<EmailTemplateAttributeConnection> EmailTemplateAttributeConnections
        {
            get { return _emailTemplateAttributeConnections  ?? (_emailTemplateAttributeConnections = CreateObjectSet<EmailTemplateAttributeConnection>("EmailTemplateAttributeConnections")); }
        }
        private ObjectSet<EmailTemplateAttributeConnection> _emailTemplateAttributeConnections;
    
        public ObjectSet<EmailTemplateAttribute> EmailTemplateAttributes
        {
            get { return _emailTemplateAttributes  ?? (_emailTemplateAttributes = CreateObjectSet<EmailTemplateAttribute>("EmailTemplateAttributes")); }
        }
        private ObjectSet<EmailTemplateAttribute> _emailTemplateAttributes;
    
        public ObjectSet<EmailSignature> EmailSignatures
        {
            get { return _emailSignatures  ?? (_emailSignatures = CreateObjectSet<EmailSignature>("EmailSignatures")); }
        }
        private ObjectSet<EmailSignature> _emailSignatures;
    
        public ObjectSet<EmailType> EmailTypes
        {
            get { return _emailTypes  ?? (_emailTypes = CreateObjectSet<EmailType>("EmailTypes")); }
        }
        private ObjectSet<EmailType> _emailTypes;
    
        public ObjectSet<AccountLanguage> AccountLanguages
        {
            get { return _accountLanguages  ?? (_accountLanguages = CreateObjectSet<AccountLanguage>("AccountLanguages")); }
        }
        private ObjectSet<AccountLanguage> _accountLanguages;
    
        public ObjectSet<AccountSponsor> AccountSponsors
        {
            get { return _accountSponsors  ?? (_accountSponsors = CreateObjectSet<AccountSponsor>("AccountSponsors")); }
        }
        private ObjectSet<AccountSponsor> _accountSponsors;
    
        public ObjectSet<AccountSponsorType> AccountSponsorTypes
        {
            get { return _accountSponsorTypes  ?? (_accountSponsorTypes = CreateObjectSet<AccountSponsorType>("AccountSponsorTypes")); }
        }
        private ObjectSet<AccountSponsorType> _accountSponsorTypes;
    
        public ObjectSet<CreditCardType> CreditCardTypes
        {
            get { return _creditCardTypes  ?? (_creditCardTypes = CreateObjectSet<CreditCardType>("CreditCardTypes")); }
        }
        private ObjectSet<CreditCardType> _creditCardTypes;
    
        public ObjectSet<MailDomain> MailDomains
        {
            get { return _mailDomains  ?? (_mailDomains = CreateObjectSet<MailDomain>("MailDomains")); }
        }
        private ObjectSet<MailDomain> _mailDomains;
    
        public ObjectSet<News> News
        {
            get { return _news  ?? (_news = CreateObjectSet<News>("News")); }
        }
        private ObjectSet<News> _news;
    
        public ObjectSet<NewsType> NewsTypes
        {
            get { return _newsTypes  ?? (_newsTypes = CreateObjectSet<NewsType>("NewsTypes")); }
        }
        private ObjectSet<NewsType> _newsTypes;
    
        public ObjectSet<OrderShipmentsLog> OrderShipmentsLogs
        {
            get { return _orderShipmentsLogs  ?? (_orderShipmentsLogs = CreateObjectSet<OrderShipmentsLog>("OrderShipmentsLogs")); }
        }
        private ObjectSet<OrderShipmentsLog> _orderShipmentsLogs;
    
        public ObjectSet<OrderShipmentStatus> OrderShipmentStatuses
        {
            get { return _orderShipmentStatuses  ?? (_orderShipmentStatuses = CreateObjectSet<OrderShipmentStatus>("OrderShipmentStatuses")); }
        }
        private ObjectSet<OrderShipmentStatus> _orderShipmentStatuses;
    
        public ObjectSet<SiteSetting> SiteSettings
        {
            get { return _siteSettings  ?? (_siteSettings = CreateObjectSet<SiteSetting>("SiteSettings")); }
        }
        private ObjectSet<SiteSetting> _siteSettings;
    
        public ObjectSet<SiteSettingValue> SiteSettingValues
        {
            get { return _siteSettingValues  ?? (_siteSettingValues = CreateObjectSet<SiteSettingValue>("SiteSettingValues")); }
        }
        private ObjectSet<SiteSettingValue> _siteSettingValues;
    
        public ObjectSet<SiteStatus> SiteStatuses
        {
            get { return _siteStatuses  ?? (_siteStatuses = CreateObjectSet<SiteStatus>("SiteStatuses")); }
        }
        private ObjectSet<SiteStatus> _siteStatuses;
    
        public ObjectSet<SiteType> SiteTypes
        {
            get { return _siteTypes  ?? (_siteTypes = CreateObjectSet<SiteType>("SiteTypes")); }
        }
        private ObjectSet<SiteType> _siteTypes;
    
        public ObjectSet<SiteUrl> SiteUrls
        {
            get { return _siteUrls  ?? (_siteUrls = CreateObjectSet<SiteUrl>("SiteUrls")); }
        }
        private ObjectSet<SiteUrl> _siteUrls;
    
        public ObjectSet<UserStatus> UserStatuses
        {
            get { return _userStatuses  ?? (_userStatuses = CreateObjectSet<UserStatus>("UserStatuses")); }
        }
        private ObjectSet<UserStatus> _userStatuses;
    
        public ObjectSet<ProxyLink> ProxyLinks
        {
            get { return _proxyLinks  ?? (_proxyLinks = CreateObjectSet<ProxyLink>("ProxyLinks")); }
        }
        private ObjectSet<ProxyLink> _proxyLinks;
    
        public ObjectSet<Policy> Policies
        {
            get { return _policies  ?? (_policies = CreateObjectSet<Policy>("Policies")); }
        }
        private ObjectSet<Policy> _policies;
    
        public ObjectSet<HtmlContentHistory> HtmlContentHistories
        {
            get { return _htmlContentHistories  ?? (_htmlContentHistories = CreateObjectSet<HtmlContentHistory>("HtmlContentHistories")); }
        }
        private ObjectSet<HtmlContentHistory> _htmlContentHistories;
    
        public ObjectSet<HtmlContentStatus> HtmlContentStatuses
        {
            get { return _htmlContentStatuses  ?? (_htmlContentStatuses = CreateObjectSet<HtmlContentStatus>("HtmlContentStatuses")); }
        }
        private ObjectSet<HtmlContentStatus> _htmlContentStatuses;
    
        public ObjectSet<HtmlContentWorkflowType> HtmlContentWorkflowTypes
        {
            get { return _htmlContentWorkflowTypes  ?? (_htmlContentWorkflowTypes = CreateObjectSet<HtmlContentWorkflowType>("HtmlContentWorkflowTypes")); }
        }
        private ObjectSet<HtmlContentWorkflowType> _htmlContentWorkflowTypes;
    
        public ObjectSet<HtmlSectionChoice> HtmlSectionChoices
        {
            get { return _htmlSectionChoices  ?? (_htmlSectionChoices = CreateObjectSet<HtmlSectionChoice>("HtmlSectionChoices")); }
        }
        private ObjectSet<HtmlSectionChoice> _htmlSectionChoices;
    
        public ObjectSet<HtmlSectionEditType> HtmlSectionEditTypes
        {
            get { return _htmlSectionEditTypes  ?? (_htmlSectionEditTypes = CreateObjectSet<HtmlSectionEditType>("HtmlSectionEditTypes")); }
        }
        private ObjectSet<HtmlSectionEditType> _htmlSectionEditTypes;
    
        public ObjectSet<HtmlSection> HtmlSections
        {
            get { return _htmlSections  ?? (_htmlSections = CreateObjectSet<HtmlSection>("HtmlSections")); }
        }
        private ObjectSet<HtmlSection> _htmlSections;
    
        public ObjectSet<CalendarEventAttribute> CalendarEventAttributes
        {
            get { return _calendarEventAttributes  ?? (_calendarEventAttributes = CreateObjectSet<CalendarEventAttribute>("CalendarEventAttributes")); }
        }
        private ObjectSet<CalendarEventAttribute> _calendarEventAttributes;
    
        public ObjectSet<CalendarEvent> CalendarEvents
        {
            get { return _calendarEvents  ?? (_calendarEvents = CreateObjectSet<CalendarEvent>("CalendarEvents")); }
        }
        private ObjectSet<CalendarEvent> _calendarEvents;
    
        public ObjectSet<AccountEmailLog> AccountEmailLogs
        {
            get { return _accountEmailLogs  ?? (_accountEmailLogs = CreateObjectSet<AccountEmailLog>("AccountEmailLogs")); }
        }
        private ObjectSet<AccountEmailLog> _accountEmailLogs;
    
        public ObjectSet<AccountListValue> AccountListValues
        {
            get { return _accountListValues  ?? (_accountListValues = CreateObjectSet<AccountListValue>("AccountListValues")); }
        }
        private ObjectSet<AccountListValue> _accountListValues;
    
        public ObjectSet<CorporateUser> CorporateUsers
        {
            get { return _corporateUsers  ?? (_corporateUsers = CreateObjectSet<CorporateUser>("CorporateUsers")); }
        }
        private ObjectSet<CorporateUser> _corporateUsers;
    
        public ObjectSet<ReturnReason> ReturnReasons
        {
            get { return _returnReasons  ?? (_returnReasons = CreateObjectSet<ReturnReason>("ReturnReasons")); }
        }
        private ObjectSet<ReturnReason> _returnReasons;
    
        public ObjectSet<ReturnType> ReturnTypes
        {
            get { return _returnTypes  ?? (_returnTypes = CreateObjectSet<ReturnType>("ReturnTypes")); }
        }
        private ObjectSet<ReturnType> _returnTypes;
    
        public ObjectSet<AccountStatusChangeReason> AccountStatusChangeReasons
        {
            get { return _accountStatusChangeReasons  ?? (_accountStatusChangeReasons = CreateObjectSet<AccountStatusChangeReason>("AccountStatusChangeReasons")); }
        }
        private ObjectSet<AccountStatusChangeReason> _accountStatusChangeReasons;
    
        public ObjectSet<OrderItemReturn> OrderItemReturns
        {
            get { return _orderItemReturns  ?? (_orderItemReturns = CreateObjectSet<OrderItemReturn>("OrderItemReturns")); }
        }
        private ObjectSet<OrderItemReturn> _orderItemReturns;
    
        public ObjectSet<RoleType> RoleTypes
        {
            get { return _roleTypes  ?? (_roleTypes = CreateObjectSet<RoleType>("RoleTypes")); }
        }
        private ObjectSet<RoleType> _roleTypes;
    
        public ObjectSet<TermTranslation> TermTranslations
        {
            get { return _termTranslations  ?? (_termTranslations = CreateObjectSet<TermTranslation>("TermTranslations")); }
        }
        private ObjectSet<TermTranslation> _termTranslations;
    
        public ObjectSet<SiteStatusChangeReason> SiteStatusChangeReasons
        {
            get { return _siteStatusChangeReasons  ?? (_siteStatusChangeReasons = CreateObjectSet<SiteStatusChangeReason>("SiteStatusChangeReasons")); }
        }
        private ObjectSet<SiteStatusChangeReason> _siteStatusChangeReasons;
    
        public ObjectSet<UserFunctionOverride> UserFunctionOverrides
        {
            get { return _userFunctionOverrides  ?? (_userFunctionOverrides = CreateObjectSet<UserFunctionOverride>("UserFunctionOverrides")); }
        }
        private ObjectSet<UserFunctionOverride> _userFunctionOverrides;
    
        public ObjectSet<Catalog> Catalogs
        {
            get { return _catalogs  ?? (_catalogs = CreateObjectSet<Catalog>("Catalogs")); }
        }
        private ObjectSet<Catalog> _catalogs;
    
        public ObjectSet<Category> Categories
        {
            get { return _categories  ?? (_categories = CreateObjectSet<Category>("Categories")); }
        }
        private ObjectSet<Category> _categories;
    
        public ObjectSet<CategoryTranslation> CategoryTranslations
        {
            get { return _categoryTranslations  ?? (_categoryTranslations = CreateObjectSet<CategoryTranslation>("CategoryTranslations")); }
        }
        private ObjectSet<CategoryTranslation> _categoryTranslations;
    
        public ObjectSet<DescriptionTranslation> DescriptionTranslations
        {
            get { return _descriptionTranslations  ?? (_descriptionTranslations = CreateObjectSet<DescriptionTranslation>("DescriptionTranslations")); }
        }
        private ObjectSet<DescriptionTranslation> _descriptionTranslations;
    
        public ObjectSet<ProductFile> ProductFiles
        {
            get { return _productFiles  ?? (_productFiles = CreateObjectSet<ProductFile>("ProductFiles")); }
        }
        private ObjectSet<ProductFile> _productFiles;
    
        public ObjectSet<ProductFileType> ProductFileTypes
        {
            get { return _productFileTypes  ?? (_productFileTypes = CreateObjectSet<ProductFileType>("ProductFileTypes")); }
        }
        private ObjectSet<ProductFileType> _productFileTypes;
    
        public ObjectSet<ProductRelation> ProductRelations
        {
            get { return _productRelations  ?? (_productRelations = CreateObjectSet<ProductRelation>("ProductRelations")); }
        }
        private ObjectSet<ProductRelation> _productRelations;
    
        public ObjectSet<ProductRelationsType> ProductRelationsTypes
        {
            get { return _productRelationsTypes  ?? (_productRelationsTypes = CreateObjectSet<ProductRelationsType>("ProductRelationsTypes")); }
        }
        private ObjectSet<ProductRelationsType> _productRelationsTypes;
    
        public ObjectSet<StoreFront> StoreFronts
        {
            get { return _storeFronts  ?? (_storeFronts = CreateObjectSet<StoreFront>("StoreFronts")); }
        }
        private ObjectSet<StoreFront> _storeFronts;
    
        public ObjectSet<WarehouseProduct> WarehouseProducts
        {
            get { return _warehouseProducts  ?? (_warehouseProducts = CreateObjectSet<WarehouseProduct>("WarehouseProducts")); }
        }
        private ObjectSet<WarehouseProduct> _warehouseProducts;
    
        public ObjectSet<TaxCategory> TaxCategories
        {
            get { return _taxCategories  ?? (_taxCategories = CreateObjectSet<TaxCategory>("TaxCategories")); }
        }
        private ObjectSet<TaxCategory> _taxCategories;
    
        public ObjectSet<ProductBase> ProductBases
        {
            get { return _productBases  ?? (_productBases = CreateObjectSet<ProductBase>("ProductBases")); }
        }
        private ObjectSet<ProductBase> _productBases;
    
        public ObjectSet<Testimonial> Testimonials
        {
            get { return _testimonials  ?? (_testimonials = CreateObjectSet<Testimonial>("Testimonials")); }
        }
        private ObjectSet<Testimonial> _testimonials;
    
        public ObjectSet<Product> Products
        {
            get { return _products  ?? (_products = CreateObjectSet<Product>("Products")); }
        }
        private ObjectSet<Product> _products;
    
        public ObjectSet<AccountPublicContactInfo> AccountPublicContactInfoes
        {
            get { return _accountPublicContactInfoes  ?? (_accountPublicContactInfoes = CreateObjectSet<AccountPublicContactInfo>("AccountPublicContactInfoes")); }
        }
        private ObjectSet<AccountPublicContactInfo> _accountPublicContactInfoes;
    
        public ObjectSet<PriceRelationshipType> PriceRelationshipTypes
        {
            get { return _priceRelationshipTypes  ?? (_priceRelationshipTypes = CreateObjectSet<PriceRelationshipType>("PriceRelationshipTypes")); }
        }
        private ObjectSet<PriceRelationshipType> _priceRelationshipTypes;
    
        public ObjectSet<AccountPriceType> AccountPriceTypes
        {
            get { return _accountPriceTypes  ?? (_accountPriceTypes = CreateObjectSet<AccountPriceType>("AccountPriceTypes")); }
        }
        private ObjectSet<AccountPriceType> _accountPriceTypes;
    
        public ObjectSet<NoteType> NoteTypes
        {
            get { return _noteTypes  ?? (_noteTypes = CreateObjectSet<NoteType>("NoteTypes")); }
        }
        private ObjectSet<NoteType> _noteTypes;
    
        public ObjectSet<AuditChangeType> AuditChangeTypes
        {
            get { return _auditChangeTypes  ?? (_auditChangeTypes = CreateObjectSet<AuditChangeType>("AuditChangeTypes")); }
        }
        private ObjectSet<AuditChangeType> _auditChangeTypes;
    
        public ObjectSet<AuditLog> AuditLogs
        {
            get { return _auditLogs  ?? (_auditLogs = CreateObjectSet<AuditLog>("AuditLogs")); }
        }
        private ObjectSet<AuditLog> _auditLogs;
    
        public ObjectSet<AuditMachineName> AuditMachineNames
        {
            get { return _auditMachineNames  ?? (_auditMachineNames = CreateObjectSet<AuditMachineName>("AuditMachineNames")); }
        }
        private ObjectSet<AuditMachineName> _auditMachineNames;
    
        public ObjectSet<AuditSqlUserName> AuditSqlUserNames
        {
            get { return _auditSqlUserNames  ?? (_auditSqlUserNames = CreateObjectSet<AuditSqlUserName>("AuditSqlUserNames")); }
        }
        private ObjectSet<AuditSqlUserName> _auditSqlUserNames;
    
        public ObjectSet<AuditTableColumn> AuditTableColumns
        {
            get { return _auditTableColumns  ?? (_auditTableColumns = CreateObjectSet<AuditTableColumn>("AuditTableColumns")); }
        }
        private ObjectSet<AuditTableColumn> _auditTableColumns;
    
        public ObjectSet<AuditTable> AuditTables
        {
            get { return _auditTables  ?? (_auditTables = CreateObjectSet<AuditTable>("AuditTables")); }
        }
        private ObjectSet<AuditTable> _auditTables;
    
        public ObjectSet<PageTranslation> PageTranslations
        {
            get { return _pageTranslations  ?? (_pageTranslations = CreateObjectSet<PageTranslation>("PageTranslations")); }
        }
        private ObjectSet<PageTranslation> _pageTranslations;
    
        public ObjectSet<HtmlElement> HtmlElements
        {
            get { return _htmlElements  ?? (_htmlElements = CreateObjectSet<HtmlElement>("HtmlElements")); }
        }
        private ObjectSet<HtmlElement> _htmlElements;
    
        public ObjectSet<HtmlElementType> HtmlElementTypes
        {
            get { return _htmlElementTypes  ?? (_htmlElementTypes = CreateObjectSet<HtmlElementType>("HtmlElementTypes")); }
        }
        private ObjectSet<HtmlElementType> _htmlElementTypes;
    
        public ObjectSet<CategoryType> CategoryTypes
        {
            get { return _categoryTypes  ?? (_categoryTypes = CreateObjectSet<CategoryType>("CategoryTypes")); }
        }
        private ObjectSet<CategoryType> _categoryTypes;
    
        public ObjectSet<HtmlSectionContent> HtmlSectionContents
        {
            get { return _htmlSectionContents  ?? (_htmlSectionContents = CreateObjectSet<HtmlSectionContent>("HtmlSectionContents")); }
        }
        private ObjectSet<HtmlSectionContent> _htmlSectionContents;
    
        public ObjectSet<AutoshipScheduleDay> AutoshipScheduleDays
        {
            get { return _autoshipScheduleDays  ?? (_autoshipScheduleDays = CreateObjectSet<AutoshipScheduleDay>("AutoshipScheduleDays")); }
        }
        private ObjectSet<AutoshipScheduleDay> _autoshipScheduleDays;
    
        public ObjectSet<AutoshipSchedule> AutoshipSchedules
        {
            get { return _autoshipSchedules  ?? (_autoshipSchedules = CreateObjectSet<AutoshipSchedule>("AutoshipSchedules")); }
        }
        private ObjectSet<AutoshipSchedule> _autoshipSchedules;
    
        public ObjectSet<ErrorLog> ErrorLogs
        {
            get { return _errorLogs  ?? (_errorLogs = CreateObjectSet<ErrorLog>("ErrorLogs")); }
        }
        private ObjectSet<ErrorLog> _errorLogs;
    
        public ObjectSet<CatalogItem> CatalogItems
        {
            get { return _catalogItems  ?? (_catalogItems = CreateObjectSet<CatalogItem>("CatalogItems")); }
        }
        private ObjectSet<CatalogItem> _catalogItems;
    
        public ObjectSet<AutoshipBatch> AutoshipBatches
        {
            get { return _autoshipBatches  ?? (_autoshipBatches = CreateObjectSet<AutoshipBatch>("AutoshipBatches")); }
        }
        private ObjectSet<AutoshipBatch> _autoshipBatches;
    
        public ObjectSet<AutoshipLog> AutoshipLogs
        {
            get { return _autoshipLogs  ?? (_autoshipLogs = CreateObjectSet<AutoshipLog>("AutoshipLogs")); }
        }
        private ObjectSet<AutoshipLog> _autoshipLogs;
    
        public ObjectSet<IntervalType> IntervalTypes
        {
            get { return _intervalTypes  ?? (_intervalTypes = CreateObjectSet<IntervalType>("IntervalTypes")); }
        }
        private ObjectSet<IntervalType> _intervalTypes;
    
        public ObjectSet<ListValueType> ListValueTypes
        {
            get { return _listValueTypes  ?? (_listValueTypes = CreateObjectSet<ListValueType>("ListValueTypes")); }
        }
        private ObjectSet<ListValueType> _listValueTypes;
    
        public ObjectSet<TaxDataSource> TaxDataSources
        {
            get { return _taxDataSources  ?? (_taxDataSources = CreateObjectSet<TaxDataSource>("TaxDataSources")); }
        }
        private ObjectSet<TaxDataSource> _taxDataSources;
    
        public ObjectSet<AutoshipScheduleProduct> AutoshipScheduleProducts
        {
            get { return _autoshipScheduleProducts  ?? (_autoshipScheduleProducts = CreateObjectSet<AutoshipScheduleProduct>("AutoshipScheduleProducts")); }
        }
        private ObjectSet<AutoshipScheduleProduct> _autoshipScheduleProducts;
    
        public ObjectSet<OrderItem> OrderItems
        {
            get { return _orderItems  ?? (_orderItems = CreateObjectSet<OrderItem>("OrderItems")); }
        }
        private ObjectSet<OrderItem> _orderItems;
    
        public ObjectSet<Order> Orders
        {
            get { return _orders  ?? (_orders = CreateObjectSet<Order>("Orders")); }
        }
        private ObjectSet<Order> _orders;
    
        public ObjectSet<Navigation> Navigations
        {
            get { return _navigations  ?? (_navigations = CreateObjectSet<Navigation>("Navigations")); }
        }
        private ObjectSet<Navigation> _navigations;
    
        public ObjectSet<NavigationTranslation> NavigationTranslations
        {
            get { return _navigationTranslations  ?? (_navigationTranslations = CreateObjectSet<NavigationTranslation>("NavigationTranslations")); }
        }
        private ObjectSet<NavigationTranslation> _navigationTranslations;
    
        public ObjectSet<AutoshipScheduleType> AutoshipScheduleTypes
        {
            get { return _autoshipScheduleTypes  ?? (_autoshipScheduleTypes = CreateObjectSet<AutoshipScheduleType>("AutoshipScheduleTypes")); }
        }
        private ObjectSet<AutoshipScheduleType> _autoshipScheduleTypes;
    
        public ObjectSet<Warehouse> Warehouses
        {
            get { return _warehouses  ?? (_warehouses = CreateObjectSet<Warehouse>("Warehouses")); }
        }
        private ObjectSet<Warehouse> _warehouses;
    
        public ObjectSet<TaxCache> TaxCaches
        {
            get { return _taxCaches  ?? (_taxCaches = CreateObjectSet<TaxCache>("TaxCaches")); }
        }
        private ObjectSet<TaxCache> _taxCaches;
    
        public ObjectSet<Address> Addresses
        {
            get { return _addresses  ?? (_addresses = CreateObjectSet<Address>("Addresses")); }
        }
        private ObjectSet<Address> _addresses;
    
        public ObjectSet<AccountContactTag> AccountContactTags
        {
            get { return _accountContactTags  ?? (_accountContactTags = CreateObjectSet<AccountContactTag>("AccountContactTags")); }
        }
        private ObjectSet<AccountContactTag> _accountContactTags;
    
        public ObjectSet<Site> Sites
        {
            get { return _sites  ?? (_sites = CreateObjectSet<Site>("Sites")); }
        }
        private ObjectSet<Site> _sites;
    
        public ObjectSet<HtmlContentWorkflow> HtmlContentWorkflows
        {
            get { return _htmlContentWorkflows  ?? (_htmlContentWorkflows = CreateObjectSet<HtmlContentWorkflow>("HtmlContentWorkflows")); }
        }
        private ObjectSet<HtmlContentWorkflow> _htmlContentWorkflows;
    
        public ObjectSet<HtmlContent> HtmlContents
        {
            get { return _htmlContents  ?? (_htmlContents = CreateObjectSet<HtmlContent>("HtmlContents")); }
        }
        private ObjectSet<HtmlContent> _htmlContents;
    
        public ObjectSet<HtmlContentEditorType> HtmlContentEditorTypes
        {
            get { return _htmlContentEditorTypes  ?? (_htmlContentEditorTypes = CreateObjectSet<HtmlContentEditorType>("HtmlContentEditorTypes")); }
        }
        private ObjectSet<HtmlContentEditorType> _htmlContentEditorTypes;
    
        public ObjectSet<AccountReportType> AccountReportTypes
        {
            get { return _accountReportTypes  ?? (_accountReportTypes = CreateObjectSet<AccountReportType>("AccountReportTypes")); }
        }
        private ObjectSet<AccountReportType> _accountReportTypes;
    
        public ObjectSet<SiteWidget> SiteWidgets
        {
            get { return _siteWidgets  ?? (_siteWidgets = CreateObjectSet<SiteWidget>("SiteWidgets")); }
        }
        private ObjectSet<SiteWidget> _siteWidgets;
    
        public ObjectSet<UserSiteWidget> UserSiteWidgets
        {
            get { return _userSiteWidgets  ?? (_userSiteWidgets = CreateObjectSet<UserSiteWidget>("UserSiteWidgets")); }
        }
        private ObjectSet<UserSiteWidget> _userSiteWidgets;
    
        public ObjectSet<Widget> Widgets
        {
            get { return _widgets  ?? (_widgets = CreateObjectSet<Widget>("Widgets")); }
        }
        private ObjectSet<Widget> _widgets;
    
        public ObjectSet<Note> Notes
        {
            get { return _notes  ?? (_notes = CreateObjectSet<Note>("Notes")); }
        }
        private ObjectSet<Note> _notes;
    
        public ObjectSet<OrderCustomerType> OrderCustomerTypes
        {
            get { return _orderCustomerTypes  ?? (_orderCustomerTypes = CreateObjectSet<OrderCustomerType>("OrderCustomerTypes")); }
        }
        private ObjectSet<OrderCustomerType> _orderCustomerTypes;
    
        public ObjectSet<Party> Parties
        {
            get { return _parties  ?? (_parties = CreateObjectSet<Party>("Parties")); }
        }
        private ObjectSet<Party> _parties;
    
        public ObjectSet<ProductBackOrderBehavior> ProductBackOrderBehaviors
        {
            get { return _productBackOrderBehaviors  ?? (_productBackOrderBehaviors = CreateObjectSet<ProductBackOrderBehavior>("ProductBackOrderBehaviors")); }
        }
        private ObjectSet<ProductBackOrderBehavior> _productBackOrderBehaviors;
    
        public ObjectSet<Commissions_AccountTitles_View> Commissions_AccountTitles_View
        {
            get { return _commissions_AccountTitles_View  ?? (_commissions_AccountTitles_View = CreateObjectSet<Commissions_AccountTitles_View>("Commissions_AccountTitles_View")); }
        }
        private ObjectSet<Commissions_AccountTitles_View> _commissions_AccountTitles_View;
    
        public ObjectSet<NewsletterTrackingStatistic> NewsletterTrackingStatistics
        {
            get { return _newsletterTrackingStatistics  ?? (_newsletterTrackingStatistics = CreateObjectSet<NewsletterTrackingStatistic>("NewsletterTrackingStatistics")); }
        }
        private ObjectSet<NewsletterTrackingStatistic> _newsletterTrackingStatistics;
    
        public ObjectSet<OptOut> OptOuts
        {
            get { return _optOuts  ?? (_optOuts = CreateObjectSet<OptOut>("OptOuts")); }
        }
        private ObjectSet<OptOut> _optOuts;
    
        public ObjectSet<OptOutType> OptOutTypes
        {
            get { return _optOutTypes  ?? (_optOutTypes = CreateObjectSet<OptOutType>("OptOutTypes")); }
        }
        private ObjectSet<OptOutType> _optOutTypes;
    
        public ObjectSet<EmailBodyTextType> EmailBodyTextTypes
        {
            get { return _emailBodyTextTypes  ?? (_emailBodyTextTypes = CreateObjectSet<EmailBodyTextType>("EmailBodyTextTypes")); }
        }
        private ObjectSet<EmailBodyTextType> _emailBodyTextTypes;
    
        public ObjectSet<AccountPolicy> AccountPolicies
        {
            get { return _accountPolicies  ?? (_accountPolicies = CreateObjectSet<AccountPolicy>("AccountPolicies")); }
        }
        private ObjectSet<AccountPolicy> _accountPolicies;
    
        public ObjectSet<DistributionList> DistributionLists
        {
            get { return _distributionLists  ?? (_distributionLists = CreateObjectSet<DistributionList>("DistributionLists")); }
        }
        private ObjectSet<DistributionList> _distributionLists;
    
        public ObjectSet<DistributionListType> DistributionListTypes
        {
            get { return _distributionListTypes  ?? (_distributionListTypes = CreateObjectSet<DistributionListType>("DistributionListTypes")); }
        }
        private ObjectSet<DistributionListType> _distributionListTypes;
    
        public ObjectSet<DistributionSubscriber> DistributionSubscribers
        {
            get { return _distributionSubscribers  ?? (_distributionSubscribers = CreateObjectSet<DistributionSubscriber>("DistributionSubscribers")); }
        }
        private ObjectSet<DistributionSubscriber> _distributionSubscribers;
    
        public ObjectSet<CampaignSubscriber> CampaignSubscribers
        {
            get { return _campaignSubscribers  ?? (_campaignSubscribers = CreateObjectSet<CampaignSubscriber>("CampaignSubscribers")); }
        }
        private ObjectSet<CampaignSubscriber> _campaignSubscribers;
    
        public ObjectSet<Autoresponder> Autoresponders
        {
            get { return _autoresponders  ?? (_autoresponders = CreateObjectSet<Autoresponder>("Autoresponders")); }
        }
        private ObjectSet<Autoresponder> _autoresponders;
    
        public ObjectSet<AutoresponderType> AutoresponderTypes
        {
            get { return _autoresponderTypes  ?? (_autoresponderTypes = CreateObjectSet<AutoresponderType>("AutoresponderTypes")); }
        }
        private ObjectSet<AutoresponderType> _autoresponderTypes;
    
        public ObjectSet<AutoresponderMessage> AutoresponderMessages
        {
            get { return _autoresponderMessages  ?? (_autoresponderMessages = CreateObjectSet<AutoresponderMessage>("AutoresponderMessages")); }
        }
        private ObjectSet<AutoresponderMessage> _autoresponderMessages;
    
        public ObjectSet<AutoresponderMessageToken> AutoresponderMessageTokens
        {
            get { return _autoresponderMessageTokens  ?? (_autoresponderMessageTokens = CreateObjectSet<AutoresponderMessageToken>("AutoresponderMessageTokens")); }
        }
        private ObjectSet<AutoresponderMessageToken> _autoresponderMessageTokens;
    
        public ObjectSet<EmailTemplateType> EmailTemplateTypes
        {
            get { return _emailTemplateTypes  ?? (_emailTemplateTypes = CreateObjectSet<EmailTemplateType>("EmailTemplateTypes")); }
        }
        private ObjectSet<EmailTemplateType> _emailTemplateTypes;
    
        public ObjectSet<AccountTag> AccountTags
        {
            get { return _accountTags  ?? (_accountTags = CreateObjectSet<AccountTag>("AccountTags")); }
        }
        private ObjectSet<AccountTag> _accountTags;
    
        public ObjectSet<AccountSource> AccountSources
        {
            get { return _accountSources  ?? (_accountSources = CreateObjectSet<AccountSource>("AccountSources")); }
        }
        private ObjectSet<AccountSource> _accountSources;
    
        public ObjectSet<PartyRsvp> PartyRsvps
        {
            get { return _partyRsvps  ?? (_partyRsvps = CreateObjectSet<PartyRsvp>("PartyRsvps")); }
        }
        private ObjectSet<PartyRsvp> _partyRsvps;
    
        public ObjectSet<PartyGuest> PartyGuests
        {
            get { return _partyGuests  ?? (_partyGuests = CreateObjectSet<PartyGuest>("PartyGuests")); }
        }
        private ObjectSet<PartyGuest> _partyGuests;
    
        public ObjectSet<ShippingRateType> ShippingRateTypes
        {
            get { return _shippingRateTypes  ?? (_shippingRateTypes = CreateObjectSet<ShippingRateType>("ShippingRateTypes")); }
        }
        private ObjectSet<ShippingRateType> _shippingRateTypes;
    
        public ObjectSet<DynamicKitGroupRule> DynamicKitGroupRules
        {
            get { return _dynamicKitGroupRules  ?? (_dynamicKitGroupRules = CreateObjectSet<DynamicKitGroupRule>("DynamicKitGroupRules")); }
        }
        private ObjectSet<DynamicKitGroupRule> _dynamicKitGroupRules;
    
        public ObjectSet<DynamicKitGroup> DynamicKitGroups
        {
            get { return _dynamicKitGroups  ?? (_dynamicKitGroups = CreateObjectSet<DynamicKitGroup>("DynamicKitGroups")); }
        }
        private ObjectSet<DynamicKitGroup> _dynamicKitGroups;
    
        public ObjectSet<DynamicKit> DynamicKits
        {
            get { return _dynamicKits  ?? (_dynamicKits = CreateObjectSet<DynamicKit>("DynamicKits")); }
        }
        private ObjectSet<DynamicKit> _dynamicKits;
    
        public ObjectSet<HostessRewardRule> HostessRewardRules
        {
            get { return _hostessRewardRules  ?? (_hostessRewardRules = CreateObjectSet<HostessRewardRule>("HostessRewardRules")); }
        }
        private ObjectSet<HostessRewardRule> _hostessRewardRules;
    
        public ObjectSet<HostessRewardRuleType> HostessRewardRuleTypes
        {
            get { return _hostessRewardRuleTypes  ?? (_hostessRewardRuleTypes = CreateObjectSet<HostessRewardRuleType>("HostessRewardRuleTypes")); }
        }
        private ObjectSet<HostessRewardRuleType> _hostessRewardRuleTypes;
    
        public ObjectSet<HostessRewardType> HostessRewardTypes
        {
            get { return _hostessRewardTypes  ?? (_hostessRewardTypes = CreateObjectSet<HostessRewardType>("HostessRewardTypes")); }
        }
        private ObjectSet<HostessRewardType> _hostessRewardTypes;
    
        public ObjectSet<LogisticsProvider> LogisticsProviders
        {
            get { return _logisticsProviders  ?? (_logisticsProviders = CreateObjectSet<LogisticsProvider>("LogisticsProviders")); }
        }
        private ObjectSet<LogisticsProvider> _logisticsProviders;
    
        public ObjectSet<OrderPaymentResult> OrderPaymentResults
        {
            get { return _orderPaymentResults  ?? (_orderPaymentResults = CreateObjectSet<OrderPaymentResult>("OrderPaymentResults")); }
        }
        private ObjectSet<OrderPaymentResult> _orderPaymentResults;
    
        public ObjectSet<AddressTaxOverride> AddressTaxOverrides
        {
            get { return _addressTaxOverrides  ?? (_addressTaxOverrides = CreateObjectSet<AddressTaxOverride>("AddressTaxOverrides")); }
        }
        private ObjectSet<AddressTaxOverride> _addressTaxOverrides;
    
        public ObjectSet<CampaignActionQueueHistory> CampaignActionQueueHistories
        {
            get { return _campaignActionQueueHistories  ?? (_campaignActionQueueHistories = CreateObjectSet<CampaignActionQueueHistory>("CampaignActionQueueHistories")); }
        }
        private ObjectSet<CampaignActionQueueHistory> _campaignActionQueueHistories;
    
        public ObjectSet<CampaignActionQueueItem> CampaignActionQueueItems
        {
            get { return _campaignActionQueueItems  ?? (_campaignActionQueueItems = CreateObjectSet<CampaignActionQueueItem>("CampaignActionQueueItems")); }
        }
        private ObjectSet<CampaignActionQueueItem> _campaignActionQueueItems;
    
        public ObjectSet<CampaignActionType> CampaignActionTypes
        {
            get { return _campaignActionTypes  ?? (_campaignActionTypes = CreateObjectSet<CampaignActionType>("CampaignActionTypes")); }
        }
        private ObjectSet<CampaignActionType> _campaignActionTypes;
    
        public ObjectSet<DomainEventQueueItem> DomainEventQueueItems
        {
            get { return _domainEventQueueItems  ?? (_domainEventQueueItems = CreateObjectSet<DomainEventQueueItem>("DomainEventQueueItems")); }
        }
        private ObjectSet<DomainEventQueueItem> _domainEventQueueItems;
    
        public ObjectSet<DomainEventType> DomainEventTypes
        {
            get { return _domainEventTypes  ?? (_domainEventTypes = CreateObjectSet<DomainEventType>("DomainEventTypes")); }
        }
        private ObjectSet<DomainEventType> _domainEventTypes;
    
        public ObjectSet<EventContext> EventContexts
        {
            get { return _eventContexts  ?? (_eventContexts = CreateObjectSet<EventContext>("EventContexts")); }
        }
        private ObjectSet<EventContext> _eventContexts;
    
        public ObjectSet<CampaignOptOut> CampaignOptOuts
        {
            get { return _campaignOptOuts  ?? (_campaignOptOuts = CreateObjectSet<CampaignOptOut>("CampaignOptOuts")); }
        }
        private ObjectSet<CampaignOptOut> _campaignOptOuts;
    
        public ObjectSet<QueueItemPriority> QueueItemPriorities
        {
            get { return _queueItemPriorities  ?? (_queueItemPriorities = CreateObjectSet<QueueItemPriority>("QueueItemPriorities")); }
        }
        private ObjectSet<QueueItemPriority> _queueItemPriorities;
    
        public ObjectSet<QueueItemStatus> QueueItemStatuses
        {
            get { return _queueItemStatuses  ?? (_queueItemStatuses = CreateObjectSet<QueueItemStatus>("QueueItemStatuses")); }
        }
        private ObjectSet<QueueItemStatus> _queueItemStatuses;
    
        public ObjectSet<EmailCampaignAction> EmailCampaignActions
        {
            get { return _emailCampaignActions  ?? (_emailCampaignActions = CreateObjectSet<EmailCampaignAction>("EmailCampaignActions")); }
        }
        private ObjectSet<EmailCampaignAction> _emailCampaignActions;
    
        public ObjectSet<SupportTicketCategory> SupportTicketCategories
        {
            get { return _supportTicketCategories  ?? (_supportTicketCategories = CreateObjectSet<SupportTicketCategory>("SupportTicketCategories")); }
        }
        private ObjectSet<SupportTicketCategory> _supportTicketCategories;
    
        public ObjectSet<SupportTicketPriority> SupportTicketPriorities
        {
            get { return _supportTicketPriorities  ?? (_supportTicketPriorities = CreateObjectSet<SupportTicketPriority>("SupportTicketPriorities")); }
        }
        private ObjectSet<SupportTicketPriority> _supportTicketPriorities;
    
        public ObjectSet<SupportTicket> SupportTickets
        {
            get { return _supportTickets  ?? (_supportTickets = CreateObjectSet<SupportTicket>("SupportTickets")); }
        }
        private ObjectSet<SupportTicket> _supportTickets;
    
        public ObjectSet<SupportTicketStatus> SupportTicketStatuses
        {
            get { return _supportTicketStatuses  ?? (_supportTicketStatuses = CreateObjectSet<SupportTicketStatus>("SupportTicketStatuses")); }
        }
        private ObjectSet<SupportTicketStatus> _supportTicketStatuses;
    
        public ObjectSet<AccountReport> AccountReports
        {
            get { return _accountReports  ?? (_accountReports = CreateObjectSet<AccountReport>("AccountReports")); }
        }
        private ObjectSet<AccountReport> _accountReports;
    
        public ObjectSet<CampaignAction> CampaignActions
        {
            get { return _campaignActions  ?? (_campaignActions = CreateObjectSet<CampaignAction>("CampaignActions")); }
        }
        private ObjectSet<CampaignAction> _campaignActions;
    
        public ObjectSet<CampaignActionTokenValue> CampaignActionTokenValues
        {
            get { return _campaignActionTokenValues  ?? (_campaignActionTokenValues = CreateObjectSet<CampaignActionTokenValue>("CampaignActionTokenValues")); }
        }
        private ObjectSet<CampaignActionTokenValue> _campaignActionTokenValues;
    
        public ObjectSet<EmailTemplateTranslation> EmailTemplateTranslations
        {
            get { return _emailTemplateTranslations  ?? (_emailTemplateTranslations = CreateObjectSet<EmailTemplateTranslation>("EmailTemplateTranslations")); }
        }
        private ObjectSet<EmailTemplateTranslation> _emailTemplateTranslations;
    
        public ObjectSet<TimeUnitType> TimeUnitTypes
        {
            get { return _timeUnitTypes  ?? (_timeUnitTypes = CreateObjectSet<TimeUnitType>("TimeUnitTypes")); }
        }
        private ObjectSet<TimeUnitType> _timeUnitTypes;
    
        public ObjectSet<Token> Tokens
        {
            get { return _tokens  ?? (_tokens = CreateObjectSet<Token>("Tokens")); }
        }
        private ObjectSet<Token> _tokens;
    
        public ObjectSet<EmailTemplate> EmailTemplates
        {
            get { return _emailTemplates  ?? (_emailTemplates = CreateObjectSet<EmailTemplate>("EmailTemplates")); }
        }
        private ObjectSet<EmailTemplate> _emailTemplates;
    
        public ObjectSet<AutoresponderTranslation> AutoresponderTranslations
        {
            get { return _autoresponderTranslations  ?? (_autoresponderTranslations = CreateObjectSet<AutoresponderTranslation>("AutoresponderTranslations")); }
        }
        private ObjectSet<AutoresponderTranslation> _autoresponderTranslations;
    
        public ObjectSet<CampaignEmail> CampaignEmails
        {
            get { return _campaignEmails  ?? (_campaignEmails = CreateObjectSet<CampaignEmail>("CampaignEmails")); }
        }
        private ObjectSet<CampaignEmail> _campaignEmails;
    
        public ObjectSet<Campaign> Campaigns
        {
            get { return _campaigns  ?? (_campaigns = CreateObjectSet<Campaign>("Campaigns")); }
        }
        private ObjectSet<Campaign> _campaigns;
    
        public ObjectSet<EmailTemplateToken> EmailTemplateTokens
        {
            get { return _emailTemplateTokens  ?? (_emailTemplateTokens = CreateObjectSet<EmailTemplateToken>("EmailTemplateTokens")); }
        }
        private ObjectSet<EmailTemplateToken> _emailTemplateTokens;
    
        public ObjectSet<Newsletter> Newsletters
        {
            get { return _newsletters  ?? (_newsletters = CreateObjectSet<Newsletter>("Newsletters")); }
        }
        private ObjectSet<Newsletter> _newsletters;
    
        public ObjectSet<Role> Roles
        {
            get { return _roles  ?? (_roles = CreateObjectSet<Role>("Roles")); }
        }
        private ObjectSet<Role> _roles;
    
        public ObjectSet<Layout> Layouts
        {
            get { return _layouts  ?? (_layouts = CreateObjectSet<Layout>("Layouts")); }
        }
        private ObjectSet<Layout> _layouts;
    
        public ObjectSet<Page> Pages
        {
            get { return _pages  ?? (_pages = CreateObjectSet<Page>("Pages")); }
        }
        private ObjectSet<Page> _pages;
    
        public ObjectSet<AlertTemplate> AlertTemplates
        {
            get { return _alertTemplates  ?? (_alertTemplates = CreateObjectSet<AlertTemplate>("AlertTemplates")); }
        }
        private ObjectSet<AlertTemplate> _alertTemplates;
    
        public ObjectSet<AlertTemplateTranslation> AlertTemplateTranslations
        {
            get { return _alertTemplateTranslations  ?? (_alertTemplateTranslations = CreateObjectSet<AlertTemplateTranslation>("AlertTemplateTranslations")); }
        }
        private ObjectSet<AlertTemplateTranslation> _alertTemplateTranslations;
    
        public ObjectSet<AlertPriority> AlertPriorities
        {
            get { return _alertPriorities  ?? (_alertPriorities = CreateObjectSet<AlertPriority>("AlertPriorities")); }
        }
        private ObjectSet<AlertPriority> _alertPriorities;
    
        public ObjectSet<NavigationType> NavigationTypes
        {
            get { return _navigationTypes  ?? (_navigationTypes = CreateObjectSet<NavigationType>("NavigationTypes")); }
        }
        private ObjectSet<NavigationType> _navigationTypes;
    
        public ObjectSet<CacheDependency> CacheDependencies
        {
            get { return _cacheDependencies  ?? (_cacheDependencies = CreateObjectSet<CacheDependency>("CacheDependencies")); }
        }
        private ObjectSet<CacheDependency> _cacheDependencies;
    
        public ObjectSet<PageType> PageTypes
        {
            get { return _pageTypes  ?? (_pageTypes = CreateObjectSet<PageType>("PageTypes")); }
        }
        private ObjectSet<PageType> _pageTypes;
    
        public ObjectSet<AccountDevice> AccountDevices
        {
            get { return _accountDevices  ?? (_accountDevices = CreateObjectSet<AccountDevice>("AccountDevices")); }
        }
        private ObjectSet<AccountDevice> _accountDevices;
    
        public ObjectSet<DeviceNotification> DeviceNotifications
        {
            get { return _deviceNotifications  ?? (_deviceNotifications = CreateObjectSet<DeviceNotification>("DeviceNotifications")); }
        }
        private ObjectSet<DeviceNotification> _deviceNotifications;
    
        public ObjectSet<DeviceType> DeviceTypes
        {
            get { return _deviceTypes  ?? (_deviceTypes = CreateObjectSet<DeviceType>("DeviceTypes")); }
        }
        private ObjectSet<DeviceType> _deviceTypes;
    
        public ObjectSet<OrderShipmentPackageItem> OrderShipmentPackageItems
        {
            get { return _orderShipmentPackageItems  ?? (_orderShipmentPackageItems = CreateObjectSet<OrderShipmentPackageItem>("OrderShipmentPackageItems")); }
        }
        private ObjectSet<OrderShipmentPackageItem> _orderShipmentPackageItems;
    
        public ObjectSet<OrderShipmentPackage> OrderShipmentPackages
        {
            get { return _orderShipmentPackages  ?? (_orderShipmentPackages = CreateObjectSet<OrderShipmentPackage>("OrderShipmentPackages")); }
        }
        private ObjectSet<OrderShipmentPackage> _orderShipmentPackages;
    
        public ObjectSet<Brand> Brands
        {
            get { return _brands  ?? (_brands = CreateObjectSet<Brand>("Brands")); }
        }
        private ObjectSet<Brand> _brands;
    
        public ObjectSet<Merchant> Merchants
        {
            get { return _merchants  ?? (_merchants = CreateObjectSet<Merchant>("Merchants")); }
        }
        private ObjectSet<Merchant> _merchants;
    
        public ObjectSet<PublicationChannel> PublicationChannels
        {
            get { return _publicationChannels  ?? (_publicationChannels = CreateObjectSet<PublicationChannel>("PublicationChannels")); }
        }
        private ObjectSet<PublicationChannel> _publicationChannels;
    
        public ObjectSet<RedemptionMethod> RedemptionMethods
        {
            get { return _redemptionMethods  ?? (_redemptionMethods = CreateObjectSet<RedemptionMethod>("RedemptionMethods")); }
        }
        private ObjectSet<RedemptionMethod> _redemptionMethods;
    
        public ObjectSet<Redemption> Redemptions
        {
            get { return _redemptions  ?? (_redemptions = CreateObjectSet<Redemption>("Redemptions")); }
        }
        private ObjectSet<Redemption> _redemptions;
    
        public ObjectSet<Statistic> Statistics
        {
            get { return _statistics  ?? (_statistics = CreateObjectSet<Statistic>("Statistics")); }
        }
        private ObjectSet<Statistic> _statistics;
    
        public ObjectSet<StatisticType> StatisticTypes
        {
            get { return _statisticTypes  ?? (_statisticTypes = CreateObjectSet<StatisticType>("StatisticTypes")); }
        }
        private ObjectSet<StatisticType> _statisticTypes;
    
        public ObjectSet<StatisticValue> StatisticValues
        {
            get { return _statisticValues  ?? (_statisticValues = CreateObjectSet<StatisticValue>("StatisticValues")); }
        }
        private ObjectSet<StatisticValue> _statisticValues;
    
        public ObjectSet<StatisticValueType> StatisticValueTypes
        {
            get { return _statisticValueTypes  ?? (_statisticValueTypes = CreateObjectSet<StatisticValueType>("StatisticValueTypes")); }
        }
        private ObjectSet<StatisticValueType> _statisticValueTypes;
    
        public ObjectSet<AddressProperty> AddressProperties
        {
            get { return _addressProperties  ?? (_addressProperties = CreateObjectSet<AddressProperty>("AddressProperties")); }
        }
        private ObjectSet<AddressProperty> _addressProperties;
    
        public ObjectSet<AddressPropertyType> AddressPropertyTypes
        {
            get { return _addressPropertyTypes  ?? (_addressPropertyTypes = CreateObjectSet<AddressPropertyType>("AddressPropertyTypes")); }
        }
        private ObjectSet<AddressPropertyType> _addressPropertyTypes;
    
        public ObjectSet<ProductMerchantLocationCache> ProductMerchantLocationCaches
        {
            get { return _productMerchantLocationCaches  ?? (_productMerchantLocationCaches = CreateObjectSet<ProductMerchantLocationCache>("ProductMerchantLocationCaches")); }
        }
        private ObjectSet<ProductMerchantLocationCache> _productMerchantLocationCaches;
    
        public ObjectSet<OrderItemParentType> OrderItemParentTypes
        {
            get { return _orderItemParentTypes  ?? (_orderItemParentTypes = CreateObjectSet<OrderItemParentType>("OrderItemParentTypes")); }
        }
        private ObjectSet<OrderItemParentType> _orderItemParentTypes;
    
        public ObjectSet<AccountProperty> AccountProperties
        {
            get { return _accountProperties  ?? (_accountProperties = CreateObjectSet<AccountProperty>("AccountProperties")); }
        }
        private ObjectSet<AccountProperty> _accountProperties;
    
        public ObjectSet<AccountPropertyType> AccountPropertyTypes
        {
            get { return _accountPropertyTypes  ?? (_accountPropertyTypes = CreateObjectSet<AccountPropertyType>("AccountPropertyTypes")); }
        }
        private ObjectSet<AccountPropertyType> _accountPropertyTypes;
    
        public ObjectSet<AccountPropertyValue> AccountPropertyValues
        {
            get { return _accountPropertyValues  ?? (_accountPropertyValues = CreateObjectSet<AccountPropertyValue>("AccountPropertyValues")); }
        }
        private ObjectSet<AccountPropertyValue> _accountPropertyValues;
    
        public ObjectSet<FileResource> FileResources
        {
            get { return _fileResources  ?? (_fileResources = CreateObjectSet<FileResource>("FileResources")); }
        }
        private ObjectSet<FileResource> _fileResources;
    
        public ObjectSet<FileResourceType> FileResourceTypes
        {
            get { return _fileResourceTypes  ?? (_fileResourceTypes = CreateObjectSet<FileResourceType>("FileResourceTypes")); }
        }
        private ObjectSet<FileResourceType> _fileResourceTypes;
    
        public ObjectSet<OrderItemProperty> OrderItemProperties
        {
            get { return _orderItemProperties  ?? (_orderItemProperties = CreateObjectSet<OrderItemProperty>("OrderItemProperties")); }
        }
        private ObjectSet<OrderItemProperty> _orderItemProperties;
    
        public ObjectSet<OrderItemPropertyType> OrderItemPropertyTypes
        {
            get { return _orderItemPropertyTypes  ?? (_orderItemPropertyTypes = CreateObjectSet<OrderItemPropertyType>("OrderItemPropertyTypes")); }
        }
        private ObjectSet<OrderItemPropertyType> _orderItemPropertyTypes;
    
        public ObjectSet<OrderItemPropertyValue> OrderItemPropertyValues
        {
            get { return _orderItemPropertyValues  ?? (_orderItemPropertyValues = CreateObjectSet<OrderItemPropertyValue>("OrderItemPropertyValues")); }
        }
        private ObjectSet<OrderItemPropertyValue> _orderItemPropertyValues;
    
        public ObjectSet<CatalogType> CatalogTypes
        {
            get { return _catalogTypes  ?? (_catalogTypes = CreateObjectSet<CatalogType>("CatalogTypes")); }
        }
        private ObjectSet<CatalogType> _catalogTypes;
    
        public ObjectSet<MarketStoreFront> MarketStoreFronts
        {
            get { return _marketStoreFronts  ?? (_marketStoreFronts = CreateObjectSet<MarketStoreFront>("MarketStoreFronts")); }
        }
        private ObjectSet<MarketStoreFront> _marketStoreFronts;
    
        public ObjectSet<FileResourceProperty> FileResourceProperties
        {
            get { return _fileResourceProperties  ?? (_fileResourceProperties = CreateObjectSet<FileResourceProperty>("FileResourceProperties")); }
        }
        private ObjectSet<FileResourceProperty> _fileResourceProperties;
    
        public ObjectSet<FileResourcePropertyType> FileResourcePropertyTypes
        {
            get { return _fileResourcePropertyTypes  ?? (_fileResourcePropertyTypes = CreateObjectSet<FileResourcePropertyType>("FileResourcePropertyTypes")); }
        }
        private ObjectSet<FileResourcePropertyType> _fileResourcePropertyTypes;
    
        public ObjectSet<AutoshipOrder> AutoshipOrders
        {
            get { return _autoshipOrders  ?? (_autoshipOrders = CreateObjectSet<AutoshipOrder>("AutoshipOrders")); }
        }
        private ObjectSet<AutoshipOrder> _autoshipOrders;
    
        public ObjectSet<DynamicKitPricingType> DynamicKitPricingTypes
        {
            get { return _dynamicKitPricingTypes  ?? (_dynamicKitPricingTypes = CreateObjectSet<DynamicKitPricingType>("DynamicKitPricingTypes")); }
        }
        private ObjectSet<DynamicKitPricingType> _dynamicKitPricingTypes;
    
        public ObjectSet<HtmlInputType> HtmlInputTypes
        {
            get { return _htmlInputTypes  ?? (_htmlInputTypes = CreateObjectSet<HtmlInputType>("HtmlInputTypes")); }
        }
        private ObjectSet<HtmlInputType> _htmlInputTypes;
    
        public ObjectSet<ProductBasePropertyValue> ProductBasePropertyValues
        {
            get { return _productBasePropertyValues  ?? (_productBasePropertyValues = CreateObjectSet<ProductBasePropertyValue>("ProductBasePropertyValues")); }
        }
        private ObjectSet<ProductBasePropertyValue> _productBasePropertyValues;
    
        public ObjectSet<ProductBaseProperty> ProductBaseProperties
        {
            get { return _productBaseProperties  ?? (_productBaseProperties = CreateObjectSet<ProductBaseProperty>("ProductBaseProperties")); }
        }
        private ObjectSet<ProductBaseProperty> _productBaseProperties;
    
        public ObjectSet<TaxCacheOverride> TaxCacheOverrides
        {
            get { return _taxCacheOverrides  ?? (_taxCacheOverrides = CreateObjectSet<TaxCacheOverride>("TaxCacheOverrides")); }
        }
        private ObjectSet<TaxCacheOverride> _taxCacheOverrides;
    
        public ObjectSet<GiftCard> GiftCards
        {
            get { return _giftCards  ?? (_giftCards = CreateObjectSet<GiftCard>("GiftCards")); }
        }
        private ObjectSet<GiftCard> _giftCards;
    
        public ObjectSet<OrderItemPrice> OrderItemPrices
        {
            get { return _orderItemPrices  ?? (_orderItemPrices = CreateObjectSet<OrderItemPrice>("OrderItemPrices")); }
        }
        private ObjectSet<OrderItemPrice> _orderItemPrices;
    
        public ObjectSet<NewsTypeLanguageSort> NewsTypeLanguageSorts
        {
            get { return _newsTypeLanguageSorts  ?? (_newsTypeLanguageSorts = CreateObjectSet<NewsTypeLanguageSort>("NewsTypeLanguageSorts")); }
        }
        private ObjectSet<NewsTypeLanguageSort> _newsTypeLanguageSorts;
    
        public ObjectSet<AlertCampaignAction> AlertCampaignActions
        {
            get { return _alertCampaignActions  ?? (_alertCampaignActions = CreateObjectSet<AlertCampaignAction>("AlertCampaignActions")); }
        }
        private ObjectSet<AlertCampaignAction> _alertCampaignActions;
    
        public ObjectSet<AccountAlert> AccountAlerts
        {
            get { return _accountAlerts  ?? (_accountAlerts = CreateObjectSet<AccountAlert>("AccountAlerts")); }
        }
        private ObjectSet<AccountAlert> _accountAlerts;
    
        public ObjectSet<DomainEventTypeCategory> DomainEventTypeCategories
        {
            get { return _domainEventTypeCategories  ?? (_domainEventTypeCategories = CreateObjectSet<DomainEventTypeCategory>("DomainEventTypeCategories")); }
        }
        private ObjectSet<DomainEventTypeCategory> _domainEventTypeCategories;
    
        public ObjectSet<OrderAdjustmentOrderLineModification> OrderAdjustmentOrderLineModifications
        {
            get { return _orderAdjustmentOrderLineModifications  ?? (_orderAdjustmentOrderLineModifications = CreateObjectSet<OrderAdjustmentOrderLineModification>("OrderAdjustmentOrderLineModifications")); }
        }
        private ObjectSet<OrderAdjustmentOrderLineModification> _orderAdjustmentOrderLineModifications;
    
        public ObjectSet<OrderAdjustmentOrderModification> OrderAdjustmentOrderModifications
        {
            get { return _orderAdjustmentOrderModifications  ?? (_orderAdjustmentOrderModifications = CreateObjectSet<OrderAdjustmentOrderModification>("OrderAdjustmentOrderModifications")); }
        }
        private ObjectSet<OrderAdjustmentOrderModification> _orderAdjustmentOrderModifications;
    
        public ObjectSet<OrderAdjustment> OrderAdjustments
        {
            get { return _orderAdjustments  ?? (_orderAdjustments = CreateObjectSet<OrderAdjustment>("OrderAdjustments")); }
        }
        private ObjectSet<OrderAdjustment> _orderAdjustments;
    
        public ObjectSet<BankAccountType> BankAccountTypes
        {
            get { return _bankAccountTypes  ?? (_bankAccountTypes = CreateObjectSet<BankAccountType>("BankAccountTypes")); }
        }
        private ObjectSet<BankAccountType> _bankAccountTypes;
    
        public ObjectSet<ProductVariantInfo> ProductVariantInfos
        {
            get { return _productVariantInfos  ?? (_productVariantInfos = CreateObjectSet<ProductVariantInfo>("ProductVariantInfos")); }
        }
        private ObjectSet<ProductVariantInfo> _productVariantInfos;
    
        public ObjectSet<OrderItemReplacement> OrderItemReplacements
        {
            get { return _orderItemReplacements  ?? (_orderItemReplacements = CreateObjectSet<OrderItemReplacement>("OrderItemReplacements")); }
        }
        private ObjectSet<OrderItemReplacement> _orderItemReplacements;
    
        public ObjectSet<ReplacementReason> ReplacementReasons
        {
            get { return _replacementReasons  ?? (_replacementReasons = CreateObjectSet<ReplacementReason>("ReplacementReasons")); }
        }
        private ObjectSet<ReplacementReason> _replacementReasons;
    
        public ObjectSet<PromotionProduct> PromotionProducts
        {
            get { return _promotionProducts  ?? (_promotionProducts = CreateObjectSet<PromotionProduct>("PromotionProducts")); }
        }
        private ObjectSet<PromotionProduct> _promotionProducts;
    
        public ObjectSet<LocalizedKind> LocalizedKinds
        {
            get { return _localizedKinds  ?? (_localizedKinds = CreateObjectSet<LocalizedKind>("LocalizedKinds")); }
        }
        private ObjectSet<LocalizedKind> _localizedKinds;
    
        public ObjectSet<OrderItemMessageDisplayKind> OrderItemMessageDisplayKinds
        {
            get { return _orderItemMessageDisplayKinds  ?? (_orderItemMessageDisplayKinds = CreateObjectSet<OrderItemMessageDisplayKind>("OrderItemMessageDisplayKinds")); }
        }
        private ObjectSet<OrderItemMessageDisplayKind> _orderItemMessageDisplayKinds;
    
        public ObjectSet<OrderItemMessage> OrderItemMessages
        {
            get { return _orderItemMessages  ?? (_orderItemMessages = CreateObjectSet<OrderItemMessage>("OrderItemMessages")); }
        }
        private ObjectSet<OrderItemMessage> _orderItemMessages;
    
        public ObjectSet<UrlRedirect> UrlRedirects
        {
            get { return _urlRedirects  ?? (_urlRedirects = CreateObjectSet<UrlRedirect>("UrlRedirects")); }
        }
        private ObjectSet<UrlRedirect> _urlRedirects;
    
        public ObjectSet<PickupPoint> PickupPoints
        {
            get { return _pickupPoints  ?? (_pickupPoints = CreateObjectSet<PickupPoint>("PickupPoints")); }
        }
        private ObjectSet<PickupPoint> _pickupPoints;
    
        public ObjectSet<SponsorHierarchy> SponsorHierarchies
        {
            get { return _sponsorHierarchies  ?? (_sponsorHierarchies = CreateObjectSet<SponsorHierarchy>("SponsorHierarchies")); }
        }
        private ObjectSet<SponsorHierarchy> _sponsorHierarchies;
    
        public ObjectSet<AccountInfoCache> AccountInfoCache
        {
            get { return _accountInfoCache  ?? (_accountInfoCache = CreateObjectSet<AccountInfoCache>("AccountInfoCache")); }
        }
        private ObjectSet<AccountInfoCache> _accountInfoCache;
    
        public ObjectSet<PostalCodeLookup> PostalCodeLookups
        {
            get { return _postalCodeLookups  ?? (_postalCodeLookups = CreateObjectSet<PostalCodeLookup>("PostalCodeLookups")); }
        }
        private ObjectSet<PostalCodeLookup> _postalCodeLookups;
    
        public ObjectSet<KitItemPrice> KitItemPrices
        {
            get { return _kitItemPrices  ?? (_kitItemPrices = CreateObjectSet<KitItemPrice>("KitItemPrices")); }
        }
        private ObjectSet<KitItemPrice> _kitItemPrices;
    
        public ObjectSet<OrderTracking> OrderTrackings
        {
            get { return _orderTrackings  ?? (_orderTrackings = CreateObjectSet<OrderTracking>("OrderTrackings")); }
        }
        private ObjectSet<OrderTracking> _orderTrackings;
    
        public ObjectSet<WarehouseMaterialAllocation> WarehouseMaterialAllocations
        {
            get { return _warehouseMaterialAllocations  ?? (_warehouseMaterialAllocations = CreateObjectSet<WarehouseMaterialAllocation>("WarehouseMaterialAllocations")); }
        }
        private ObjectSet<WarehouseMaterialAllocation> _warehouseMaterialAllocations;
    
        public ObjectSet<WarehouseMaterial> WarehouseMaterials
        {
            get { return _warehouseMaterials  ?? (_warehouseMaterials = CreateObjectSet<WarehouseMaterial>("WarehouseMaterials")); }
        }
        private ObjectSet<WarehouseMaterial> _warehouseMaterials;
    
        public ObjectSet<Material> Materials
        {
            get { return _materials  ?? (_materials = CreateObjectSet<Material>("Materials")); }
        }
        private ObjectSet<Material> _materials;
    
        public ObjectSet<AccountSuppliedID> AccountSuppliedIDs
        {
            get { return _accountSuppliedIDs  ?? (_accountSuppliedIDs = CreateObjectSet<AccountSuppliedID>("AccountSuppliedIDs")); }
        }
        private ObjectSet<AccountSuppliedID> _accountSuppliedIDs;

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="siteID">No Metadata Documentation available.</param>
        public virtual ObjectResult<SiteSettingItem> usp_sitesettings_select_values(Nullable<int> siteID)
        {
    
            ObjectParameter siteIDParameter;
    
            if (siteID.HasValue)
            {
                siteIDParameter = new ObjectParameter("SiteID", siteID);
            }
            else
            {
                siteIDParameter = new ObjectParameter("SiteID", typeof(int));
            }
            return base.ExecuteFunction<SiteSettingItem>("usp_sitesettings_select_values", siteIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="siteID">No Metadata Documentation available.</param>
        /// <param name="title">No Metadata Documentation available.</param>
        /// <param name="value">No Metadata Documentation available.</param>
        public virtual int usp_sitesetting_save(Nullable<int> siteID, string title, string value)
        {
    
            ObjectParameter siteIDParameter;
    
            if (siteID.HasValue)
            {
                siteIDParameter = new ObjectParameter("SiteID", siteID);
            }
            else
            {
                siteIDParameter = new ObjectParameter("SiteID", typeof(int));
            }
    
            ObjectParameter titleParameter;
    
            if (title != null)
            {
                titleParameter = new ObjectParameter("Title", title);
            }
            else
            {
                titleParameter = new ObjectParameter("Title", typeof(string));
            }
    
            ObjectParameter valueParameter;
    
            if (value != null)
            {
                valueParameter = new ObjectParameter("Value", value);
            }
            else
            {
                valueParameter = new ObjectParameter("Value", typeof(string));
            }
            return base.ExecuteFunction("usp_sitesetting_save", siteIDParameter, titleParameter, valueParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="siteID">No Metadata Documentation available.</param>
        /// <param name="hTMLSectionID">No Metadata Documentation available.</param>
        /// <param name="hTMLContentID">No Metadata Documentation available.</param>
        public virtual int usp_htmlsectioncontent_choose(Nullable<int> siteID, Nullable<int> hTMLSectionID, Nullable<int> hTMLContentID)
        {
    
            ObjectParameter siteIDParameter;
    
            if (siteID.HasValue)
            {
                siteIDParameter = new ObjectParameter("SiteID", siteID);
            }
            else
            {
                siteIDParameter = new ObjectParameter("SiteID", typeof(int));
            }
    
            ObjectParameter hTMLSectionIDParameter;
    
            if (hTMLSectionID.HasValue)
            {
                hTMLSectionIDParameter = new ObjectParameter("HTMLSectionID", hTMLSectionID);
            }
            else
            {
                hTMLSectionIDParameter = new ObjectParameter("HTMLSectionID", typeof(int));
            }
    
            ObjectParameter hTMLContentIDParameter;
    
            if (hTMLContentID.HasValue)
            {
                hTMLContentIDParameter = new ObjectParameter("HTMLContentID", hTMLContentID);
            }
            else
            {
                hTMLContentIDParameter = new ObjectParameter("HTMLContentID", typeof(int));
            }
            return base.ExecuteFunction("usp_htmlsectioncontent_choose", siteIDParameter, hTMLSectionIDParameter, hTMLContentIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="statusID">No Metadata Documentation available.</param>
        public virtual ObjectResult<HtmlContentAccountStatus> usp_htmlcontent_select_content_and_distributor_by_status(Nullable<int> statusID)
        {
    
            ObjectParameter statusIDParameter;
    
            if (statusID.HasValue)
            {
                statusIDParameter = new ObjectParameter("StatusID", statusID);
            }
            else
            {
                statusIDParameter = new ObjectParameter("StatusID", typeof(int));
            }
            return base.ExecuteFunction<HtmlContentAccountStatus>("usp_htmlcontent_select_content_and_distributor_by_status", statusIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="tableName">No Metadata Documentation available.</param>
        /// <param name="pk">No Metadata Documentation available.</param>
        /// <param name="pageIndex">No Metadata Documentation available.</param>
        /// <param name="pageSize">No Metadata Documentation available.</param>
        public virtual ObjectResult<AuditLogRow> usp_get_audit_trail(string tableName, Nullable<int> pk, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
    
            ObjectParameter tableNameParameter;
    
            if (tableName != null)
            {
                tableNameParameter = new ObjectParameter("tableName", tableName);
            }
            else
            {
                tableNameParameter = new ObjectParameter("tableName", typeof(string));
            }
    
            ObjectParameter pkParameter;
    
            if (pk.HasValue)
            {
                pkParameter = new ObjectParameter("pk", pk);
            }
            else
            {
                pkParameter = new ObjectParameter("pk", typeof(int));
            }
    
            ObjectParameter pageIndexParameter;
    
            if (pageIndex.HasValue)
            {
                pageIndexParameter = new ObjectParameter("pageIndex", pageIndex);
            }
            else
            {
                pageIndexParameter = new ObjectParameter("pageIndex", typeof(int));
            }
    
            ObjectParameter pageSizeParameter;
    
            if (pageSize.HasValue)
            {
                pageSizeParameter = new ObjectParameter("pageSize", pageSize);
            }
            else
            {
                pageSizeParameter = new ObjectParameter("pageSize", typeof(int));
            }
            return base.ExecuteFunction<AuditLogRow>("usp_get_audit_trail", tableNameParameter, pkParameter, pageIndexParameter, pageSizeParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="categoryID">No Metadata Documentation available.</param>
        public virtual ObjectResult<Nullable<int>> usp_category_get_top_of_tree_id(Nullable<int> categoryID)
        {
    
            ObjectParameter categoryIDParameter;
    
            if (categoryID.HasValue)
            {
                categoryIDParameter = new ObjectParameter("CategoryID", categoryID);
            }
            else
            {
                categoryIDParameter = new ObjectParameter("CategoryID", typeof(int));
            }
            return base.ExecuteFunction<Nullable<int>>("usp_category_get_top_of_tree_id", categoryIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="categoryTreeID">No Metadata Documentation available.</param>
        public virtual ObjectResult<Nullable<int>> usp_categories_get_tree_depth(Nullable<int> categoryTreeID)
        {
    
            ObjectParameter categoryTreeIDParameter;
    
            if (categoryTreeID.HasValue)
            {
                categoryTreeIDParameter = new ObjectParameter("CategoryTreeID", categoryTreeID);
            }
            else
            {
                categoryTreeIDParameter = new ObjectParameter("CategoryTreeID", typeof(int));
            }
            return base.ExecuteFunction<Nullable<int>>("usp_categories_get_tree_depth", categoryTreeIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="categoryID">No Metadata Documentation available.</param>
        public virtual ObjectResult<Nullable<int>> usp_categories_get_tree(Nullable<int> categoryID)
        {
    
            ObjectParameter categoryIDParameter;
    
            if (categoryID.HasValue)
            {
                categoryIDParameter = new ObjectParameter("CategoryID", categoryID);
            }
            else
            {
                categoryIDParameter = new ObjectParameter("CategoryID", typeof(int));
            }
            return base.ExecuteFunction<Nullable<int>>("usp_categories_get_tree", categoryIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="accountID">No Metadata Documentation available.</param>
        public virtual ObjectResult<Nullable<int>> GetOrderAdjustmentIDsForAccountID(Nullable<int> accountID)
        {
    
            ObjectParameter accountIDParameter;
    
            if (accountID.HasValue)
            {
                accountIDParameter = new ObjectParameter("accountID", accountID);
            }
            else
            {
                accountIDParameter = new ObjectParameter("accountID", typeof(int));
            }
            return base.ExecuteFunction<Nullable<int>>("GetOrderAdjustmentIDsForAccountID", accountIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="accountID">No Metadata Documentation available.</param>
        /// <param name="query">No Metadata Documentation available.</param>
        public virtual ObjectResult<usp_accounts_search_downline_Result> usp_accounts_search_downline(Nullable<int> accountID, string query)
        {
    
            ObjectParameter accountIDParameter;
    
            if (accountID.HasValue)
            {
                accountIDParameter = new ObjectParameter("AccountID", accountID);
            }
            else
            {
                accountIDParameter = new ObjectParameter("AccountID", typeof(int));
            }
    
            ObjectParameter queryParameter;
    
            if (query != null)
            {
                queryParameter = new ObjectParameter("Query", query);
            }
            else
            {
                queryParameter = new ObjectParameter("Query", typeof(string));
            }
            return base.ExecuteFunction<usp_accounts_search_downline_Result>("usp_accounts_search_downline", accountIDParameter, queryParameter);
        }

        #endregion
    }
}
