-- ====================================================
-- **GO STATEMENTS**
-- Plain GO statements will not execute properly!!!!!
-- Please avoid using GO statements, or if you need to
-- use a GO then append a --GO to the end of the GO 
-- statement without any spaces as shown below.
--
-- i.e.   GO--GO
--
-- **TRANSACTIONS**
-- Transactions are NOT Supported! The run once logic
-- will roll back if there is a problem.
--
-- **TEMP TABLES**
-- If you want to use temporary tables please use 
-- global temp tables. 
-- 
-- i.e.   ##
-- ====================================================


