//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderRules.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rules
    {
     
        public Rules()
        {
            this.RuleValidations = new HashSet<RuleValidations>();
        }
    
        public int RuleID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Name { get; set; }
        public string TermName { get; set; }
        public int RuleStatus { get; set; }
    
        public virtual RuleStatuses RuleStatuses { get; set; }
        public virtual ICollection<RuleValidations> RuleValidations { get; set; }
    }
}
