//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderRules.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleValidationCustomerSubtotalRanges
    {
     
        public RuleValidationCustomerSubtotalRanges()
        {
            this.RuleValidationCustomerSubtotalRangeCurrencyAmounts = new HashSet<RuleValidationCustomerSubtotalRangeCurrencyAmounts>();
        }
    
        public int RuleValidationID { get; set; }
    
        public virtual ICollection<RuleValidationCustomerSubtotalRangeCurrencyAmounts> RuleValidationCustomerSubtotalRangeCurrencyAmounts { get; set; }
        public virtual RuleValidations RuleValidations { get; set; }
    }
}
