//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderRules.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleValidationStoreFrontListItems
    {
        public int RuleValidationStoreFrontListItemID { get; set; }
        public Nullable<int> RuleValidationID { get; set; }
        public int StoreFrontID { get; set; }
    
        public virtual RuleValidationStoreFrontLists RuleValidationStoreFrontLists { get; set; }
    }
}
