//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderRules.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleStatuses
    {
     
        public RuleStatuses()
        {
            this.Rules = new HashSet<Rules>();
        }
    
        public int RuleStatusID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Rules> Rules { get; set; }
    }
}
