DECLARE @NAME_{WORKSHEETID}_{COUNT}        NVARCHAR(100)

SET @NAME_{WORKSHEETID}_{COUNT}       = '{NAME}'

IF NOT EXISTS (SELECT * FROM OrderTypes WHERE Name = @NAME_{WORKSHEETID}_{COUNT})
BEGIN

	PRINT 'INSERTING ORDERTYPE - ' + @NAME_{WORKSHEETID}_{COUNT}
		
	INSERT INTO OrderTypes (Name, IsTemplate, Active) VALUES (@NAME_{WORKSHEETID}_{COUNT}, 0, 1)
	
END
ELSE
BEGIN
	
	PRINT 'ALREADY ORDERTYPE   - ' + @NAME_{WORKSHEETID}_{COUNT}

END



