DECLARE @SHIPPINGRATEGROUPNAME_{WORKSHEETID}_{COUNT} NVARCHAR(255)
DECLARE @SHIPPINGRATEGROUPDESCRIPTION_{WORKSHEETID}_{COUNT} NVARCHAR(255)
DECLARE @SHIPPINGRATEGROUPGROUPCODE_{WORKSHEETID}_{COUNT} NVARCHAR(255)

SET @SHIPPINGRATEGROUPNAME_{WORKSHEETID}_{COUNT}       = '{SHIPPINGRATEGROUPNAME}'
SET @SHIPPINGRATEGROUPDESCRIPTION_{WORKSHEETID}_{COUNT}       = '{SHIPPINGRATEGROUPDESCRIPTION}'
SET @SHIPPINGRATEGROUPGROUPCODE_{WORKSHEETID}_{COUNT}       = '{SHIPPINGRATEGROUPGROUPCODE}'

IF NOT EXISTS (SELECT * FROM ShippingRateGroups WHERE Name = @SHIPPINGRATEGROUPNAME_{WORKSHEETID}_{COUNT})
BEGIN 

	PRINT 'INSERT SHIPPING RATE GROUP           - ' + @SHIPPINGRATEGROUPNAME_{WORKSHEETID}_{COUNT}
	
	INSERT INTO [ShippingRateGroups] ([Name] ,[Description] ,[GroupCode]) 
	VALUES (@SHIPPINGRATEGROUPNAME_{WORKSHEETID}_{COUNT}, @SHIPPINGRATEGROUPDESCRIPTION_{WORKSHEETID}_{COUNT}, @SHIPPINGRATEGROUPGROUPCODE_{WORKSHEETID}_{COUNT})
	
END
ELSE
BEGIN
	
	PRINT 'ALREADY INSERTED SHIPPING RATE GROUP - ' + @SHIPPINGRATEGROUPNAME_{WORKSHEETID}_{COUNT}

END
