DECLARE @SHIPPINGORDERTYPEORDERTYPEID_{WORKSHEETID}_{COUNT} SMALLINT
DECLARE @SHIPPINGORDERTYPESHIPPINGMETHODID_{WORKSHEETID}_{COUNT} INT
DECLARE @SHIPPINGORDERTYPESHIPPINGREGIONID_{WORKSHEETID}_{COUNT} INT
DECLARE @SHIPPINGORDERTYPESHIPPINGRATEGROUPID_{WORKSHEETID}_{COUNT} INT
DECLARE @SHIPPINGORDERTYPECOUNTRYID_{WORKSHEETID}_{COUNT} INT
DECLARE @SHIPPINGORDERTYPEOVERRIDEAMOUNT_{WORKSHEETID}_{COUNT} MONEY
DECLARE @SHIPPINGORDERTYPEOVERRIDEINCLUSIVE_{WORKSHEETID}_{COUNT} BIT
DECLARE @SHIPPINGORDERTYPEALLOWDIRECTSHIPMENTS_{WORKSHEETID}_{COUNT} BIT
DECLARE @SHIPPINGORDERTYPEISDEFAULTSHIPPINGMETHOD_{WORKSHEETID}_{COUNT} BIT

SET @SHIPPINGORDERTYPEORDERTYPEID_{WORKSHEETID}_{COUNT}				= (SELECT TOP 1 OrderTypeID FROM OrderTypes WHERE Name = '{SHIPPINGORDERTYPEORDERTYPE}') 
SET @SHIPPINGORDERTYPESHIPPINGMETHODID_{WORKSHEETID}_{COUNT}		= (SELECT TOP 1 ShippingMethodID FROM ShippingMethods WHERE Name = '{SHIPPINGORDERTYPESHIPPINGMETHODNAME}')
SET @SHIPPINGORDERTYPESHIPPINGREGIONID_{WORKSHEETID}_{COUNT}		= (SELECT TOP 1 ShippingRegionID FROM ShippingRegions WHERE Name = '{SHIPPINGORDERTYPESHIPPINGREGIONNAME}') 
SET @SHIPPINGORDERTYPESHIPPINGRATEGROUPID_{WORKSHEETID}_{COUNT}		= (SELECT TOP 1 ShippingRateGroupID FROM ShippingRateGroups WHERE Name = '{SHIPPINGORDERTYPESHIPPINGRATEGROUPNAME}') 
SET @SHIPPINGORDERTYPECOUNTRYID_{WORKSHEETID}_{COUNT}				= (SELECT TOP 1 CountryID FROM Countries WHERE Name = '{SHIPPINGORDERTYPECOUNTRYNAME}')
SET @SHIPPINGORDERTYPEOVERRIDEAMOUNT_{WORKSHEETID}_{COUNT}			= {SHIPPINGORDERTYPEOVERRIDEAMOUNT}
SET @SHIPPINGORDERTYPEOVERRIDEINCLUSIVE_{WORKSHEETID}_{COUNT}		= {SHIPPINGORDERTYPEOVERRIDEINCLUSIVE}
SET @SHIPPINGORDERTYPEALLOWDIRECTSHIPMENTS_{WORKSHEETID}_{COUNT}	= {SHIPPINGORDERTYPEALLOWDIRECTSHIPMENTS}
SET @SHIPPINGORDERTYPEISDEFAULTSHIPPINGMETHOD_{WORKSHEETID}_{COUNT} = {SHIPPINGORDERTYPEISDEFAULTSHIPPINGMETHOD}

INSERT INTO [ShippingOrderTypes]
           ([OrderTypeID]
           ,[ShippingMethodID]
           ,[ShippingRegionID]
           ,[ShippingRateGroupID]
           ,[CountryID]
           ,[OverrideAmount]
           ,[OverrideInclusive]
           ,[AllowDirectShipments]
           ,[IsDefaultShippingMethod])
     VALUES
           (@SHIPPINGORDERTYPEORDERTYPEID_{WORKSHEETID}_{COUNT}				
           ,@SHIPPINGORDERTYPESHIPPINGMETHODID_{WORKSHEETID}_{COUNT}		
           ,@SHIPPINGORDERTYPESHIPPINGREGIONID_{WORKSHEETID}_{COUNT}		
           ,@SHIPPINGORDERTYPESHIPPINGRATEGROUPID_{WORKSHEETID}_{COUNT}		
           ,@SHIPPINGORDERTYPECOUNTRYID_{WORKSHEETID}_{COUNT}				
           ,@SHIPPINGORDERTYPEOVERRIDEAMOUNT_{WORKSHEETID}_{COUNT}			
           ,@SHIPPINGORDERTYPEOVERRIDEINCLUSIVE_{WORKSHEETID}_{COUNT}		
           ,@SHIPPINGORDERTYPEALLOWDIRECTSHIPMENTS_{WORKSHEETID}_{COUNT}	
           ,@SHIPPINGORDERTYPEISDEFAULTSHIPPINGMETHOD_{WORKSHEETID}_{COUNT})


