DECLARE @NAME_{WORKSHEETID}_{COUNT}        NVARCHAR(100)
DECLARE @WAREHOUSENAME_{WORKSHEETID}_{COUNT}        NVARCHAR(100)

SET @NAME_{WORKSHEETID}_{COUNT}       = '{NAME}'
SET @WAREHOUSENAME_{WORKSHEETID}_{COUNT} = '{WAREHOUSENAME}'

IF NOT EXISTS (SELECT * FROM ShippingRegions WHERE Name = @NAME_{WORKSHEETID}_{COUNT})
BEGIN

	PRINT 'INSERTING SHIPING REGION - ' + @NAME_{WORKSHEETID}_{COUNT}
		
	INSERT INTO ShippingRegions (Name, Description, Active, Editable, WarehouseID) 
	VALUES (@NAME_{WORKSHEETID}_{COUNT}, @NAME_{WORKSHEETID}_{COUNT}, 1, 1, (SELECT TOP 1 WarehouseID FROM Warehouses WHERE NAME = @WAREHOUSENAME_{WORKSHEETID}_{COUNT}))
	
END
ELSE
BEGIN
	
	PRINT 'ALREADY SHIPING REGION   - ' + @NAME_{WORKSHEETID}_{COUNT}

END



