DECLARE @NAME_{WORKSHEETID}_{COUNT} NVARCHAR(500)
DECLARE @DESCRIPTION_{WORKSHEETID}_{COUNT} NVARCHAR(500)
DECLARE @SHORTNAME_{WORKSHEETID}_{COUNT} NVARCHAR(500)
DECLARE @PRIORITY_{WORKSHEETID}_{COUNT} INT
DECLARE @ACCEPTPOBOXES_{WORKSHEETID}_{COUNT} BIT
DECLARE @ISWILLCALL_{WORKSHEETID}_{COUNT} BIT
DECLARE @TRACKINGURL_{WORKSHEETID}_{COUNT} NVARCHAR(500)
DECLARE @DESCRIPTIONTRANSLATIONSID_{WORKSHEETID}_{COUNT} INT
DECLARE @SHIPPINGMETHODID_{WORKSHEETID}_{COUNT} INT

SET @NAME_{WORKSHEETID}_{COUNT} = '{NAME}'
SET @DESCRIPTION_{WORKSHEETID}_{COUNT} = '{DESCRIPTION}'
SET @SHORTNAME_{WORKSHEETID}_{COUNT} = '{SHORTNAME}'
SET @PRIORITY_{WORKSHEETID}_{COUNT} = {PRIORITY}
SET @ACCEPTPOBOXES_{WORKSHEETID}_{COUNT} = {ACCEPTPOBOXES}
SET @ISWILLCALL_{WORKSHEETID}_{COUNT} = {ISWILLCALL}
SET @TRACKINGURL_{WORKSHEETID}_{COUNT} = '{TRACKINGURL}'

IF NOT EXISTS (SELECT * FROM ShippingMethods WHERE Name = @NAME_{WORKSHEETID}_{COUNT})
BEGIN

	PRINT 'INSERTING SHIPPING METHOD - ' + @NAME_{WORKSHEETID}_{COUNT}

	INSERT INTO DescriptionTranslations (LanguageID, Name, ShortDescription, LongDescription) 
	VALUES ((SELECT TOP 1 LanguageID FROM Languages WHERE Name = 'English'), @NAME_{WORKSHEETID}_{COUNT}, @DESCRIPTION_{WORKSHEETID}_{COUNT},  @DESCRIPTION_{WORKSHEETID}_{COUNT})
		
	SET @DESCRIPTIONTRANSLATIONSID_{WORKSHEETID}_{COUNT} = SCOPE_IDENTITY()

	INSERT INTO ShippingMethods (Name, ShortName, Active, IsWillCall, SortIndex, TrackingNumberBaseUrl) 
	VALUES (@NAME_{WORKSHEETID}_{COUNT}, @SHORTNAME_{WORKSHEETID}_{COUNT}, 1, @ISWILLCALL_{WORKSHEETID}_{COUNT}, @PRIORITY_{WORKSHEETID}_{COUNT}, @TRACKINGURL_{WORKSHEETID}_{COUNT})
	
	SET @SHIPPINGMETHODID_{WORKSHEETID}_{COUNT}  = SCOPE_IDENTITY()

	INSERT INTO ShippingMethodTranslations (ShippingMethodID, DescriptionTranslationID)	
	VALUES (@SHIPPINGMETHODID_{WORKSHEETID}_{COUNT}, @DESCRIPTIONTRANSLATIONSID_{WORKSHEETID}_{COUNT})

END
ELSE
BEGIN
	
	PRINT 'ALREADY INSERTED          - ' + @NAME_{WORKSHEETID}_{COUNT}

END