DECLARE @SHIPPINGRATEGROUPID_{WORKSHEETID}_{COUNT} INT
DECLARE @CURRENCYID_{WORKSHEETID}_{COUNT} INT
DECLARE @VALUENAME_{WORKSHEETID}_{COUNT} NVARCHAR(50)
DECLARE @VALUEFROM_{WORKSHEETID}_{COUNT} MONEY
DECLARE @VALUETO_{WORKSHEETID}_{COUNT} MONEY
DECLARE @SHIPPINGAMOUNT_{WORKSHEETID}_{COUNT} MONEY
DECLARE @DIRECTSHIPMENTFEE_{WORKSHEETID}_{COUNT} MONEY
DECLARE @HANDLINGFEE_{WORKSHEETID}_{COUNT} MONEY
DECLARE @INCREMENTALAMOUNT_{WORKSHEETID}_{COUNT} MONEY
DECLARE @INCREMENTALFEE_{WORKSHEETID}_{COUNT} MONEY
DECLARE @SHIPPINGPERCENTAGE_{WORKSHEETID}_{COUNT} MONEY
DECLARE @SHIPPINGRATETYPEID_{WORKSHEETID}_{COUNT} INT
DECLARE @SHIPPINGRATEGROUPMINIMUMAMOUNT_{WORKSHEETID}_{COUNT} MONEY

SET @SHIPPINGRATEGROUPID_{WORKSHEETID}_{COUNT} = (SELECT TOP 1 ShippingRateGroupID FROM ShippingRateGroups WHERE Name = '{SHIPPINGRATEGROUPNAME}')
SET @CURRENCYID_{WORKSHEETID}_{COUNT} = (SELECT TOP 1 CurrencyID FROM Currencies WHERE Name = '{CURRENCYNAME}')
SET @VALUENAME_{WORKSHEETID}_{COUNT} = '{VALUENAME}'
SET @VALUEFROM_{WORKSHEETID}_{COUNT} = {VALUEFROM}
SET @VALUETO_{WORKSHEETID}_{COUNT} = {VALUETO}
SET @SHIPPINGAMOUNT_{WORKSHEETID}_{COUNT} = {SHIPPINGAMOUNT}
SET @DIRECTSHIPMENTFEE_{WORKSHEETID}_{COUNT} = {DIRECTSHIPMENTFEE}
SET @HANDLINGFEE_{WORKSHEETID}_{COUNT} = {HANDLINGFEE}
SET @INCREMENTALAMOUNT_{WORKSHEETID}_{COUNT} = {INCREMENTALAMOUNT}
SET @INCREMENTALFEE_{WORKSHEETID}_{COUNT} = {INCREMENTALFEE}
SET @SHIPPINGPERCENTAGE_{WORKSHEETID}_{COUNT} = {SHIPPINGPERCENTAGE}
SET @SHIPPINGRATETYPEID_{WORKSHEETID}_{COUNT} = {SHIPPINGRATETYPEID}
SET @SHIPPINGRATEGROUPMINIMUMAMOUNT_{WORKSHEETID}_{COUNT} = {MINIMUMAMOUNT}

INSERT INTO [ShippingRates]
           ([ShippingRateGroupID]
           ,[CurrencyID]
           ,[ValueName]
           ,[ValueFrom]
           ,[ValueTo]
           ,[ShippingAmount]
           ,[DirectShipmentFee]
           ,[HandlingFee]
           ,[IncrementalAmount]
           ,[IncrementalFee]
           ,[ShippingPercentage]
           ,[ShippingRateTypeID]
		   ,[MinimumAmount])
     VALUES
           (@SHIPPINGRATEGROUPID_{WORKSHEETID}_{COUNT}
           ,@CURRENCYID_{WORKSHEETID}_{COUNT}
           ,@VALUENAME_{WORKSHEETID}_{COUNT}
           ,@VALUEFROM_{WORKSHEETID}_{COUNT}
           ,@VALUETO_{WORKSHEETID}_{COUNT}
           ,@SHIPPINGAMOUNT_{WORKSHEETID}_{COUNT}
           ,@DIRECTSHIPMENTFEE_{WORKSHEETID}_{COUNT}
           ,@HANDLINGFEE_{WORKSHEETID}_{COUNT}
           ,@INCREMENTALAMOUNT_{WORKSHEETID}_{COUNT}
           ,@INCREMENTALFEE_{WORKSHEETID}_{COUNT}
           ,@SHIPPINGPERCENTAGE_{WORKSHEETID}_{COUNT}
           ,@SHIPPINGRATETYPEID_{WORKSHEETID}_{COUNT}
		   ,@SHIPPINGRATEGROUPMINIMUMAMOUNT_{WORKSHEETID}_{COUNT})
