DECLARE @NAME_{WORKSHEETID}_{COUNT}        NVARCHAR(255)
DECLARE @COUNTRYNAME_{WORKSHEETID}_{COUNT}        NVARCHAR(255)
DECLARE @SHIPPINGREGIONNAME_{WORKSHEETID}_{COUNT}        NVARCHAR(255)

SET @NAME_{WORKSHEETID}_{COUNT}       = '{STATECODE}'
SET @COUNTRYNAME_{WORKSHEETID}_{COUNT}       = '{COUNTRYNAME}'
SET @SHIPPINGREGIONNAME_{WORKSHEETID}_{COUNT}       = '{SHIPPINGREGIONNAME}'

IF EXISTS (SELECT * FROM StateProvinces 
WHERE StateAbbreviation = @NAME_{WORKSHEETID}_{COUNT} 
AND CountryID = (SELECT TOP 1 CountryID FROM Countries WHERE Name = @COUNTRYNAME_{WORKSHEETID}_{COUNT}))
BEGIN

	PRINT 'UPDATING STATE PROVINCE SHIPPING REGION - ' + @NAME_{WORKSHEETID}_{COUNT}
	
	UPDATE StateProvinces SET ShippingRegionID = (SELECT TOP 1 ShippingRegionID FROM ShippingRegions WHERE Name = @SHIPPINGREGIONNAME_{WORKSHEETID}_{COUNT}) 
	WHERE StateAbbreviation = @NAME_{WORKSHEETID}_{COUNT} 
	AND CountryID = (SELECT TOP 1 CountryID FROM Countries WHERE Name = @COUNTRYNAME_{WORKSHEETID}_{COUNT}) 
	
END
ELSE
BEGIN
	
	PRINT 'NO STATE PROVINCE FOUND FOR            - ' + @NAME_{WORKSHEETID}_{COUNT}

END



