DECLARE @ADDRESSID_{WORKSHEETID}_{COUNT}   INT
DECLARE @NAME_{WORKSHEETID}_{COUNT}        NVARCHAR(100)
DECLARE @ACTIVE_{WORKSHEETID}_{COUNT}      BIT

DECLARE @ADDRESS1_{WORKSHEETID}_{COUNT}   NVARCHAR(500)
DECLARE @CITY_{WORKSHEETID}_{COUNT}       NVARCHAR(500)
DECLARE @COUNTRY_{WORKSHEETID}_{COUNT}    NVARCHAR(500)
DECLARE @STATE_{WORKSHEETID}_{COUNT}      NVARCHAR(500)
DECLARE @POSTALCODE_{WORKSHEETID}_{COUNT} NVARCHAR(500)

DECLARE @COUNTRYID_{WORKSHEETID}_{COUNT} INT
DECLARE @STATEPROVINCEID_{WORKSHEETID}_{COUNT} INT

SET @NAME_{WORKSHEETID}_{COUNT}       = '{NAME}'
SET @ADDRESS1_{WORKSHEETID}_{COUNT}   = '{ADDRESS1}'
SET @CITY_{WORKSHEETID}_{COUNT}       = '{CITY}'
SET @COUNTRY_{WORKSHEETID}_{COUNT}    = '{COUNTRY}'
SET @STATE_{WORKSHEETID}_{COUNT}      = '{STATE}'
SET @POSTALCODE_{WORKSHEETID}_{COUNT} = '{POSTALCODE}'

IF NOT EXISTS (SELECT * FROM Warehouses WHERE Name = @NAME_{WORKSHEETID}_{COUNT})
BEGIN

	PRINT 'INSERTING WAREHOUSE - ' + @NAME_{WORKSHEETID}_{COUNT}

	SET @COUNTRYID_{WORKSHEETID}_{COUNT} = (SELECT TOP 1 CountryID FROM Countries WHERE Name = @COUNTRY_{WORKSHEETID}_{COUNT})
	SET @STATEPROVINCEID_{WORKSHEETID}_{COUNT} = (SELECT TOP 1 StateProvinceID FROM StateProvinces WHERE CountryID = @COUNTRYID_{WORKSHEETID}_{COUNT} AND StateAbbreviation = @STATE_{WORKSHEETID}_{COUNT})
		
	INSERT INTO Addresses (Address1, AddressTypeID, City, CountryID, StateProvinceID, PostalCode, IsDefault) 
	VALUES (@ADDRESS1_{WORKSHEETID}_{COUNT}, (SELECT TOP 1 AddressTypeID FROM AddressTypes WHERE Name = 'Warehouse'), @CITY_{WORKSHEETID}_{COUNT}, @COUNTRYID_{WORKSHEETID}_{COUNT}, @STATEPROVINCEID_{WORKSHEETID}_{COUNT}, @POSTALCODE_{WORKSHEETID}_{COUNT}, 1)
		
	SET @ADDRESSID_{WORKSHEETID}_{COUNT} = SCOPE_IDENTITY()
	
	INSERT INTO Warehouses (AddressID, Name, Description, Active) 
	VALUES (@ADDRESSID_{WORKSHEETID}_{COUNT}, @NAME_{WORKSHEETID}_{COUNT}, @NAME_{WORKSHEETID}_{COUNT}, 1)
	
END
ELSE
BEGIN
	
	PRINT 'ALREADY INSERTED    - ' + @NAME_{WORKSHEETID}_{COUNT}

END