#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadyShipperIntegrationService
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ItWorksCore")]
	public partial class NetstepsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLogisticsCommunication(LogisticsCommunication instance);
    partial void UpdateLogisticsCommunication(LogisticsCommunication instance);
    partial void DeleteLogisticsCommunication(LogisticsCommunication instance);
    #endregion
		
		public NetstepsDataContext() : 
				base(global::ReadyShipperIntegrationService.Properties.Settings.Default.ItWorksCoreConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NetstepsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NetstepsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NetstepsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NetstepsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LogisticsCommunication> LogisticsCommunications
		{
			get
			{
				return this.GetTable<LogisticsCommunication>();
			}
		}
		
		public System.Data.Linq.Table<VwLogisticsProviderImport> VwLogisticsProviderImports
		{
			get
			{
				return this.GetTable<VwLogisticsProviderImport>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UspErrorLogsInsert")]
		public int UspErrorLogsInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="LogDateUTC", DbType="DateTime")] System.Nullable<System.DateTime> logDateUTC, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExceptionTypeName", DbType="VarChar(255)")] string exceptionTypeName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Source", DbType="VarChar(500)")] string source, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="VarChar(5000)")] string message)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), logDateUTC, exceptionTypeName, source, message);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UspLogisticsCommunicationInsert")]
		public int UspLogisticsCommunicationInsert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="NVarChar(MAX)")] string message)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), message);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UspLogisticsCommunicationUpdate")]
		public int UspLogisticsCommunicationUpdate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="NVarChar(MAX)")] string message)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), message);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UspSelectLogisticsProviderOrderItems")]
		public ISingleResult<VwLogisticsProviderImport> UspSelectLogisticsProviderOrderItems()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<VwLogisticsProviderImport>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UspSelectVwLogisticsProviderOrderItemsByOrderID")]
		public ISingleResult<VwLogisticsProviderImport> UspSelectVwLogisticsProviderOrderItemsByOrderID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID);
			return ((ISingleResult<VwLogisticsProviderImport>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UspSelectVwLogisticsProviderOrderHeader")]
		public ISingleResult<VwLogisticsProviderImport> UspSelectVwLogisticsProviderOrderHeader()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<VwLogisticsProviderImport>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UspUpdateOrderShipments")]
		public int UspUpdateOrderShipments([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModifiedByUserID", DbType="Int")] System.Nullable<int> modifiedByUserID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Values", DbType="VarChar(MAX)")] string values)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), modifiedByUserID, orderID, values);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspLogisticsRecordTrackingNumberByOrderID")]
		public int uspLogisticsRecordTrackingNumberByOrderID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OrderID", DbType="Int")] System.Nullable<int> orderID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TrackingNumber", DbType="NVarChar(1000)")] string trackingNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), orderID, trackingNumber);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LogisticsCommunication")]
	public partial class LogisticsCommunication : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _LogisticsCommunicationID;
		
		private string _Message;
		
		private System.DateTime _CreatedOn;
		
		private System.DateTime _UpdatedOn;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLogisticsCommunicationIDChanging(int value);
    partial void OnLogisticsCommunicationIDChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnCreatedOnChanging(System.DateTime value);
    partial void OnCreatedOnChanged();
    partial void OnUpdatedOnChanging(System.DateTime value);
    partial void OnUpdatedOnChanged();
    #endregion
		
		public LogisticsCommunication()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogisticsCommunicationID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int LogisticsCommunicationID
		{
			get
			{
				return this._LogisticsCommunicationID;
			}
			set
			{
				if ((this._LogisticsCommunicationID != value))
				{
					this.OnLogisticsCommunicationIDChanging(value);
					this.SendPropertyChanging();
					this._LogisticsCommunicationID = value;
					this.SendPropertyChanged("LogisticsCommunicationID");
					this.OnLogisticsCommunicationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Message", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOn", DbType="DateTime2 NOT NULL")]
		public System.DateTime CreatedOn
		{
			get
			{
				return this._CreatedOn;
			}
			set
			{
				if ((this._CreatedOn != value))
				{
					this.OnCreatedOnChanging(value);
					this.SendPropertyChanging();
					this._CreatedOn = value;
					this.SendPropertyChanged("CreatedOn");
					this.OnCreatedOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedOn", DbType="DateTime2 NOT NULL")]
		public System.DateTime UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this.OnUpdatedOnChanging(value);
					this.SendPropertyChanging();
					this._UpdatedOn = value;
					this.SendPropertyChanged("UpdatedOn");
					this.OnUpdatedOnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VwLogisticsProviderImport")]
	public partial class VwLogisticsProviderImport
	{
		
		private int _DistributorID;
		
		private int _CustomerNumber;
		
		private int _PrimaryID;
		
		private string _BillAddress1;
		
		private string _BillAddress2;
		
		private string _BillCity;
		
		private string _Billcountry;
		
		private string _BillFirst;
		
		private string _BillLast;
		
		private string _BillCompany;
		
		private string _BillZip;
		
		private string _BillState;
		
		private string _BillPhone;
		
		private string _BillEmail;
		
		private string _ShipAddress1;
		
		private string _ShipAddress2;
		
		private string _ShipCity;
		
		private string _ShipCountry;
		
		private string _ShipFirst;
		
		private string _ShipLast;
		
		private string _ShipCompany;
		
		private string _ShipZip;
		
		private string _ShipState;
		
		private string _ShipPhone;
		
		private string _ShipEmail;
		
		private string _ShipType;
		
		private string _ShipVia;
		
		private System.Nullable<decimal> _BilledShipping;
		
		private System.Nullable<decimal> _Tax;
		
		private System.Nullable<decimal> _DeclaredValue;
		
		private System.Nullable<decimal> _TotalSale;
		
		private System.DateTime _DateofSale;
		
		private string _MESSAGE;
		
		private string _Product;
		
		private int _Quantity;
		
		private System.Nullable<double> _Weight;
		
		private string _MerchandiseDescription;
		
		private decimal _Price;
		
		private string _PaymentMethod;
		
		private string _AutoShip;
		
		private string _Title;
		
		private string _Residential;
		
		private string _CommodityCode;
		
		private string _PerkPoints;
		
		private string _CountryOfOrigin;
		
		private string _DeliveryConfirmation;
		
		private string _Warehouse;
		
		private string _URL;
		
		private int _OrderItemID;
		
		public VwLogisticsProviderImport()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DistributorID", DbType="Int NOT NULL")]
		public int DistributorID
		{
			get
			{
				return this._DistributorID;
			}
			set
			{
				if ((this._DistributorID != value))
				{
					this._DistributorID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerNumber", DbType="Int NOT NULL")]
		public int CustomerNumber
		{
			get
			{
				return this._CustomerNumber;
			}
			set
			{
				if ((this._CustomerNumber != value))
				{
					this._CustomerNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimaryID", DbType="Int NOT NULL")]
		public int PrimaryID
		{
			get
			{
				return this._PrimaryID;
			}
			set
			{
				if ((this._PrimaryID != value))
				{
					this._PrimaryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillAddress1", DbType="NVarChar(200)")]
		public string BillAddress1
		{
			get
			{
				return this._BillAddress1;
			}
			set
			{
				if ((this._BillAddress1 != value))
				{
					this._BillAddress1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillAddress2", DbType="NVarChar(200)")]
		public string BillAddress2
		{
			get
			{
				return this._BillAddress2;
			}
			set
			{
				if ((this._BillAddress2 != value))
				{
					this._BillAddress2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillCity", DbType="NVarChar(200)")]
		public string BillCity
		{
			get
			{
				return this._BillCity;
			}
			set
			{
				if ((this._BillCity != value))
				{
					this._BillCity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Billcountry", DbType="NVarChar(6)")]
		public string Billcountry
		{
			get
			{
				return this._Billcountry;
			}
			set
			{
				if ((this._Billcountry != value))
				{
					this._Billcountry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillFirst", DbType="NVarChar(100)")]
		public string BillFirst
		{
			get
			{
				return this._BillFirst;
			}
			set
			{
				if ((this._BillFirst != value))
				{
					this._BillFirst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillLast", DbType="NVarChar(100)")]
		public string BillLast
		{
			get
			{
				return this._BillLast;
			}
			set
			{
				if ((this._BillLast != value))
				{
					this._BillLast = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillCompany", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string BillCompany
		{
			get
			{
				return this._BillCompany;
			}
			set
			{
				if ((this._BillCompany != value))
				{
					this._BillCompany = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillZip", DbType="NVarChar(20)")]
		public string BillZip
		{
			get
			{
				return this._BillZip;
			}
			set
			{
				if ((this._BillZip != value))
				{
					this._BillZip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillState", DbType="NVarChar(10)")]
		public string BillState
		{
			get
			{
				return this._BillState;
			}
			set
			{
				if ((this._BillState != value))
				{
					this._BillState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillPhone", DbType="NVarChar(50)")]
		public string BillPhone
		{
			get
			{
				return this._BillPhone;
			}
			set
			{
				if ((this._BillPhone != value))
				{
					this._BillPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillEmail", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string BillEmail
		{
			get
			{
				return this._BillEmail;
			}
			set
			{
				if ((this._BillEmail != value))
				{
					this._BillEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipAddress1", DbType="NVarChar(200)")]
		public string ShipAddress1
		{
			get
			{
				return this._ShipAddress1;
			}
			set
			{
				if ((this._ShipAddress1 != value))
				{
					this._ShipAddress1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipAddress2", DbType="NVarChar(200)")]
		public string ShipAddress2
		{
			get
			{
				return this._ShipAddress2;
			}
			set
			{
				if ((this._ShipAddress2 != value))
				{
					this._ShipAddress2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipCity", DbType="NVarChar(200)")]
		public string ShipCity
		{
			get
			{
				return this._ShipCity;
			}
			set
			{
				if ((this._ShipCity != value))
				{
					this._ShipCity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipCountry", DbType="NVarChar(6)")]
		public string ShipCountry
		{
			get
			{
				return this._ShipCountry;
			}
			set
			{
				if ((this._ShipCountry != value))
				{
					this._ShipCountry = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipFirst", DbType="NVarChar(100)")]
		public string ShipFirst
		{
			get
			{
				return this._ShipFirst;
			}
			set
			{
				if ((this._ShipFirst != value))
				{
					this._ShipFirst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipLast", DbType="NVarChar(100)")]
		public string ShipLast
		{
			get
			{
				return this._ShipLast;
			}
			set
			{
				if ((this._ShipLast != value))
				{
					this._ShipLast = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipCompany", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string ShipCompany
		{
			get
			{
				return this._ShipCompany;
			}
			set
			{
				if ((this._ShipCompany != value))
				{
					this._ShipCompany = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipZip", DbType="NVarChar(20)")]
		public string ShipZip
		{
			get
			{
				return this._ShipZip;
			}
			set
			{
				if ((this._ShipZip != value))
				{
					this._ShipZip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipState", DbType="NVarChar(10)")]
		public string ShipState
		{
			get
			{
				return this._ShipState;
			}
			set
			{
				if ((this._ShipState != value))
				{
					this._ShipState = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipPhone", DbType="VarChar(50)")]
		public string ShipPhone
		{
			get
			{
				return this._ShipPhone;
			}
			set
			{
				if ((this._ShipPhone != value))
				{
					this._ShipPhone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipEmail", DbType="NVarChar(250)")]
		public string ShipEmail
		{
			get
			{
				return this._ShipEmail;
			}
			set
			{
				if ((this._ShipEmail != value))
				{
					this._ShipEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipType", DbType="NVarChar(50)")]
		public string ShipType
		{
			get
			{
				return this._ShipType;
			}
			set
			{
				if ((this._ShipType != value))
				{
					this._ShipType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipVia", DbType="NVarChar(50)")]
		public string ShipVia
		{
			get
			{
				return this._ShipVia;
			}
			set
			{
				if ((this._ShipVia != value))
				{
					this._ShipVia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BilledShipping", DbType="Money")]
		public System.Nullable<decimal> BilledShipping
		{
			get
			{
				return this._BilledShipping;
			}
			set
			{
				if ((this._BilledShipping != value))
				{
					this._BilledShipping = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tax", DbType="Money")]
		public System.Nullable<decimal> Tax
		{
			get
			{
				return this._Tax;
			}
			set
			{
				if ((this._Tax != value))
				{
					this._Tax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeclaredValue", DbType="Money")]
		public System.Nullable<decimal> DeclaredValue
		{
			get
			{
				return this._DeclaredValue;
			}
			set
			{
				if ((this._DeclaredValue != value))
				{
					this._DeclaredValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalSale", DbType="Money")]
		public System.Nullable<decimal> TotalSale
		{
			get
			{
				return this._TotalSale;
			}
			set
			{
				if ((this._TotalSale != value))
				{
					this._TotalSale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateofSale", DbType="DateTime NOT NULL")]
		public System.DateTime DateofSale
		{
			get
			{
				return this._DateofSale;
			}
			set
			{
				if ((this._DateofSale != value))
				{
					this._DateofSale = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MESSAGE", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string MESSAGE
		{
			get
			{
				return this._MESSAGE;
			}
			set
			{
				if ((this._MESSAGE != value))
				{
					this._MESSAGE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Product", DbType="NVarChar(50)")]
		public string Product
		{
			get
			{
				return this._Product;
			}
			set
			{
				if ((this._Product != value))
				{
					this._Product = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int NOT NULL")]
		public int Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Float")]
		public System.Nullable<double> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this._Weight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MerchandiseDescription", DbType="NVarChar(200)")]
		public string MerchandiseDescription
		{
			get
			{
				return this._MerchandiseDescription;
			}
			set
			{
				if ((this._MerchandiseDescription != value))
				{
					this._MerchandiseDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentMethod", DbType="NVarChar(50)")]
		public string PaymentMethod
		{
			get
			{
				return this._PaymentMethod;
			}
			set
			{
				if ((this._PaymentMethod != value))
				{
					this._PaymentMethod = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AutoShip", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string AutoShip
		{
			get
			{
				return this._AutoShip;
			}
			set
			{
				if ((this._AutoShip != value))
				{
					this._AutoShip = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(250)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this._Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Residential", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string Residential
		{
			get
			{
				return this._Residential;
			}
			set
			{
				if ((this._Residential != value))
				{
					this._Residential = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommodityCode", DbType="VarChar(1) NOT NULL", CanBeNull=false)]
		public string CommodityCode
		{
			get
			{
				return this._CommodityCode;
			}
			set
			{
				if ((this._CommodityCode != value))
				{
					this._CommodityCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PerkPoints", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string PerkPoints
		{
			get
			{
				return this._PerkPoints;
			}
			set
			{
				if ((this._PerkPoints != value))
				{
					this._PerkPoints = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryOfOrigin", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string CountryOfOrigin
		{
			get
			{
				return this._CountryOfOrigin;
			}
			set
			{
				if ((this._CountryOfOrigin != value))
				{
					this._CountryOfOrigin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeliveryConfirmation", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string DeliveryConfirmation
		{
			get
			{
				return this._DeliveryConfirmation;
			}
			set
			{
				if ((this._DeliveryConfirmation != value))
				{
					this._DeliveryConfirmation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Warehouse", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string Warehouse
		{
			get
			{
				return this._Warehouse;
			}
			set
			{
				if ((this._Warehouse != value))
				{
					this._Warehouse = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="VarChar(32) NOT NULL", CanBeNull=false)]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this._URL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderItemID", DbType="Int NOT NULL")]
		public int OrderItemID
		{
			get
			{
				return this._OrderItemID;
			}
			set
			{
				if ((this._OrderItemID != value))
				{
					this._OrderItemID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
