//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace NetSteps.Data.Entities.Mail
{
    [KnownType(typeof(MailAttachment))]
    [KnownType(typeof(MailMessage))]
    [Serializable]
    public partial class MailMessageAttachment: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        public int MailMessageAttachmentID
        {
            get { return _mailMessageAttachmentID; }
            set
            {
                if (_mailMessageAttachmentID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'MailMessageAttachmentID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _mailMessageAttachmentID = value;
                    OnPropertyChanged("MailMessageAttachmentID");
                }
            }
        }
        private int _mailMessageAttachmentID;
    
        public int MailMessageID
        {
            get { return _mailMessageID; }
            set
            {
                if (_mailMessageID != value)
                {
                    ChangeTracker.RecordOriginalValue("MailMessageID", _mailMessageID);
                    if (!IsDeserializing)
                    {
                        if (MailMessage != null && MailMessage.MailMessageID != value)
                        {
                            MailMessage = null;
                        }
                    }
                    _mailMessageID = value;
                    OnPropertyChanged("MailMessageID");
                }
            }
        }
        private int _mailMessageID;
    
        public int MailAttachmentID
        {
            get { return _mailAttachmentID; }
            set
            {
                if (_mailAttachmentID != value)
                {
                    ChangeTracker.RecordOriginalValue("MailAttachmentID", _mailAttachmentID);
                    if (!IsDeserializing)
                    {
                        if (MailAttachment != null && MailAttachment.MailAttachmentID != value)
                        {
                            MailAttachment = null;
                        }
                    }
                    _mailAttachmentID = value;
                    OnPropertyChanged("MailAttachmentID");
                }
            }
        }
        private int _mailAttachmentID;

        #endregion
        #region Navigation Properties
    
            public MailAttachment MailAttachment
        {
            get { return _mailAttachment; }
            set
            {
                if (!ReferenceEquals(_mailAttachment, value))
                {
                    var previousValue = _mailAttachment;
                    _mailAttachment = value;
                    FixupMailAttachment(previousValue);
                    OnNavigationPropertyChanged("MailAttachment");
                }
            }
        }
        private MailAttachment _mailAttachment;
    
            public MailMessage MailMessage
        {
            get { return _mailMessage; }
            set
            {
                if (!ReferenceEquals(_mailMessage, value))
                {
                    var previousValue = _mailMessage;
                    _mailMessage = value;
                    FixupMailMessage(previousValue);
                    OnNavigationPropertyChanged("MailMessage");
                }
            }
        }
        private MailMessage _mailMessage;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
    
        protected virtual void ClearNavigationProperties()
        {
            MailAttachment = null;
            MailMessage = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupMailAttachment(MailAttachment previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.MailMessageAttachments.Contains(this))
            {
                previousValue.MailMessageAttachments.Remove(this);
            }
    
            if (MailAttachment != null)
            {
                if (!MailAttachment.MailMessageAttachments.Contains(this))
                {
                    MailAttachment.MailMessageAttachments.Add(this);
                }
    
                MailAttachmentID = MailAttachment.MailAttachmentID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("MailAttachment")
                    && (ChangeTracker.OriginalValues["MailAttachment"] == MailAttachment))
                {
                    ChangeTracker.OriginalValues.Remove("MailAttachment");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("MailAttachment", previousValue);
                }
                if (MailAttachment != null && !MailAttachment.ChangeTracker.ChangeTrackingEnabled)
                {
                    MailAttachment.StartTracking();
                }
            }
        }
    
        private void FixupMailMessage(MailMessage previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.MailMessageAttachments.Contains(this))
            {
                previousValue.MailMessageAttachments.Remove(this);
            }
    
            if (MailMessage != null)
            {
                if (!MailMessage.MailMessageAttachments.Contains(this))
                {
                    MailMessage.MailMessageAttachments.Add(this);
                }
    
                MailMessageID = MailMessage.MailMessageID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("MailMessage")
                    && (ChangeTracker.OriginalValues["MailMessage"] == MailMessage))
                {
                    ChangeTracker.OriginalValues.Remove("MailMessage");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("MailMessage", previousValue);
                }
                if (MailMessage != null && !MailMessage.ChangeTracker.ChangeTrackingEnabled)
                {
                    MailMessage.StartTracking();
                }
            }
        }

        #endregion
    }
}
