//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace NetSteps.Data.Entities.Mail
{
    [KnownType(typeof(MailMessageRecipientEvent))]
    [Serializable]
    public partial class MailMessageRecipientEventType: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        public short MailMessageRecipientEventTypeID
        {
            get { return _mailMessageRecipientEventTypeID; }
            set
            {
                if (_mailMessageRecipientEventTypeID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'MailMessageRecipientEventTypeID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _mailMessageRecipientEventTypeID = value;
                    OnPropertyChanged("MailMessageRecipientEventTypeID");
                }
            }
        }
        private short _mailMessageRecipientEventTypeID;
    
        public string Name
        {
            get { return _name; }
            set
            {
                if (_name != value)
                {
                    ChangeTracker.RecordOriginalValue("Name", _name);
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;
    
        public string TermName
        {
            get { return _termName; }
            set
            {
                if (_termName != value)
                {
                    ChangeTracker.RecordOriginalValue("TermName", _termName);
                    _termName = value;
                    OnPropertyChanged("TermName");
                }
            }
        }
        private string _termName;
    
        public string Description
        {
            get { return _description; }
            set
            {
                if (_description != value)
                {
                    ChangeTracker.RecordOriginalValue("Description", _description);
                    _description = value;
                    OnPropertyChanged("Description");
                }
            }
        }
        private string _description;
    
        public bool Active
        {
            get { return _active; }
            set
            {
                if (_active != value)
                {
                    ChangeTracker.RecordOriginalValue("Active", _active);
                    _active = value;
                    OnPropertyChanged("Active");
                }
            }
        }
        private bool _active;

        #endregion
        #region Navigation Properties
    
            public TrackableCollection<MailMessageRecipientEvent> MailMessageRecipientEvents
        {
            get
            {
                if (_mailMessageRecipientEvents == null)
                {
                    _mailMessageRecipientEvents = new TrackableCollection<MailMessageRecipientEvent>();
                    _mailMessageRecipientEvents.CollectionChanged += FixupMailMessageRecipientEvents;
                }
                return _mailMessageRecipientEvents;
            }
            set
            {
                if (!ReferenceEquals(_mailMessageRecipientEvents, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_mailMessageRecipientEvents != null)
                    {
                        _mailMessageRecipientEvents.CollectionChanged -= FixupMailMessageRecipientEvents;
                    }
                    _mailMessageRecipientEvents = value;
                    if (_mailMessageRecipientEvents != null)
                    {
                        _mailMessageRecipientEvents.CollectionChanged += FixupMailMessageRecipientEvents;
                    }
                    OnNavigationPropertyChanged("MailMessageRecipientEvents");
                }
            }
        }
        private TrackableCollection<MailMessageRecipientEvent> _mailMessageRecipientEvents;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
            if (_mailMessageRecipientEvents != null)
    		{
    		    _mailMessageRecipientEvents.CollectionChanged -= FixupMailMessageRecipientEvents;
                _mailMessageRecipientEvents.CollectionChanged += FixupMailMessageRecipientEvents;
            }
        }
    
    
        protected virtual void ClearNavigationProperties()
        {
            MailMessageRecipientEvents.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupMailMessageRecipientEvents(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (MailMessageRecipientEvent item in e.NewItems)
                {
                    item.MailMessageRecipientEventType = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("MailMessageRecipientEvents", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (MailMessageRecipientEvent item in e.OldItems)
                {
                    if (ReferenceEquals(item.MailMessageRecipientEventType, this))
                    {
                        item.MailMessageRecipientEventType = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("MailMessageRecipientEvents", item);
                    }
                }
            }
        }

        #endregion
    }
}
