//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.EntityClient;
using System.Data.Objects;

namespace NetSteps.Data.Entities.Mail
{
    public partial class MailEntities : ObjectContext
    {
        public const string ConnectionString = "name=MailEntities";
        public const string ContainerName = "MailEntities";
    
        #region Constructors
    
        public MailEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            Initialize();
        }
    
        public MailEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            Initialize();
        }
    
        private void Initialize()
        {
            // Creating proxies requires the use of the ProxyDataContractResolver and
            // may allow lazy loading which can expand the loaded graph during serialization.
            ContextOptions.ProxyCreationEnabled = false;
            ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
        }
    
        private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
        {
            var entity = e.Entity as IObjectWithChangeTracker;
            if (entity != null)
            {
                bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
                try
                {
                    entity.MarkAsUnchanged();
                }
                finally
                {
                    entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
                }
                this.StoreReferenceKeyValues(entity);
            }
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<AddressType> AddressTypes
        {
            get { return _addressTypes  ?? (_addressTypes = CreateObjectSet<AddressType>("MailEntities.AddressTypes")); }
        }
        private ObjectSet<AddressType> _addressTypes;
    
        public ObjectSet<MailAttachment> MailAttachments
        {
            get { return _mailAttachments  ?? (_mailAttachments = CreateObjectSet<MailAttachment>("MailEntities.MailAttachments")); }
        }
        private ObjectSet<MailAttachment> _mailAttachments;
    
        public ObjectSet<MailFolderType> MailFolderTypes
        {
            get { return _mailFolderTypes  ?? (_mailFolderTypes = CreateObjectSet<MailFolderType>("MailEntities.MailFolderTypes")); }
        }
        private ObjectSet<MailFolderType> _mailFolderTypes;
    
        public ObjectSet<MailMessageAttachment> MailMessageAttachments
        {
            get { return _mailMessageAttachments  ?? (_mailMessageAttachments = CreateObjectSet<MailMessageAttachment>("MailEntities.MailMessageAttachments")); }
        }
        private ObjectSet<MailMessageAttachment> _mailMessageAttachments;
    
        public ObjectSet<MailMessageGroupAddress> MailMessageGroupAddresses
        {
            get { return _mailMessageGroupAddresses  ?? (_mailMessageGroupAddresses = CreateObjectSet<MailMessageGroupAddress>("MailEntities.MailMessageGroupAddresses")); }
        }
        private ObjectSet<MailMessageGroupAddress> _mailMessageGroupAddresses;
    
        public ObjectSet<MailMessageGroup> MailMessageGroups
        {
            get { return _mailMessageGroups  ?? (_mailMessageGroups = CreateObjectSet<MailMessageGroup>("MailEntities.MailMessageGroups")); }
        }
        private ObjectSet<MailMessageGroup> _mailMessageGroups;
    
        public ObjectSet<MailMessageGroupStatusAudit> MailMessageGroupStatusAudits
        {
            get { return _mailMessageGroupStatusAudits  ?? (_mailMessageGroupStatusAudits = CreateObjectSet<MailMessageGroupStatusAudit>("MailEntities.MailMessageGroupStatusAudits")); }
        }
        private ObjectSet<MailMessageGroupStatusAudit> _mailMessageGroupStatusAudits;
    
        public ObjectSet<MailMessagePriority> MailMessagePriorities
        {
            get { return _mailMessagePriorities  ?? (_mailMessagePriorities = CreateObjectSet<MailMessagePriority>("MailEntities.MailMessagePriorities")); }
        }
        private ObjectSet<MailMessagePriority> _mailMessagePriorities;
    
        public ObjectSet<MailMessageType> MailMessageTypes
        {
            get { return _mailMessageTypes  ?? (_mailMessageTypes = CreateObjectSet<MailMessageType>("MailEntities.MailMessageTypes")); }
        }
        private ObjectSet<MailMessageType> _mailMessageTypes;
    
        public ObjectSet<MessageGroupStatus> MessageGroupStatus1
        {
            get { return _messageGroupStatus1  ?? (_messageGroupStatus1 = CreateObjectSet<MessageGroupStatus>("MailEntities.MessageGroupStatus1")); }
        }
        private ObjectSet<MessageGroupStatus> _messageGroupStatus1;
    
        public ObjectSet<RecipientStatus> RecipientStatus1
        {
            get { return _recipientStatus1  ?? (_recipientStatus1 = CreateObjectSet<RecipientStatus>("MailEntities.RecipientStatus1")); }
        }
        private ObjectSet<RecipientStatus> _recipientStatus1;
    
        public ObjectSet<RecipientType> RecipientTypes
        {
            get { return _recipientTypes  ?? (_recipientTypes = CreateObjectSet<RecipientType>("MailEntities.RecipientTypes")); }
        }
        private ObjectSet<RecipientType> _recipientTypes;
    
        public ObjectSet<MailMessage> MailMessages
        {
            get { return _mailMessages  ?? (_mailMessages = CreateObjectSet<MailMessage>("MailEntities.MailMessages")); }
        }
        private ObjectSet<MailMessage> _mailMessages;
    
        public ObjectSet<MailMessageRecipientEvent> MailMessageRecipientEvents
        {
            get { return _mailMessageRecipientEvents  ?? (_mailMessageRecipientEvents = CreateObjectSet<MailMessageRecipientEvent>("MailEntities.MailMessageRecipientEvents")); }
        }
        private ObjectSet<MailMessageRecipientEvent> _mailMessageRecipientEvents;
    
        public ObjectSet<MailMessageRecipientEventType> MailMessageRecipientEventTypes
        {
            get { return _mailMessageRecipientEventTypes  ?? (_mailMessageRecipientEventTypes = CreateObjectSet<MailMessageRecipientEventType>("MailEntities.MailMessageRecipientEventTypes")); }
        }
        private ObjectSet<MailMessageRecipientEventType> _mailMessageRecipientEventTypes;
    
        public ObjectSet<SitesAccount> SitesAccounts
        {
            get { return _sitesAccounts  ?? (_sitesAccounts = CreateObjectSet<SitesAccount>("MailEntities.SitesAccounts")); }
        }
        private ObjectSet<SitesAccount> _sitesAccounts;
    
        public ObjectSet<SitesCampaignSubscriber> SitesCampaignSubscribers
        {
            get { return _sitesCampaignSubscribers  ?? (_sitesCampaignSubscribers = CreateObjectSet<SitesCampaignSubscriber>("MailEntities.SitesCampaignSubscribers")); }
        }
        private ObjectSet<SitesCampaignSubscriber> _sitesCampaignSubscribers;

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mailMessageID">No Metadata Documentation available.</param>
        public virtual int usp_MailMessageMarkRead(Nullable<int> mailMessageID)
        {
    
            ObjectParameter mailMessageIDParameter;
    
            if (mailMessageID.HasValue)
            {
                mailMessageIDParameter = new ObjectParameter("MailMessageID", mailMessageID);
            }
            else
            {
                mailMessageIDParameter = new ObjectParameter("MailMessageID", typeof(int));
            }
            return base.ExecuteFunction("usp_MailMessageMarkRead", mailMessageIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mailMessageID">No Metadata Documentation available.</param>
        public virtual int usp_DeleteMailMessage(Nullable<int> mailMessageID)
        {
    
            ObjectParameter mailMessageIDParameter;
    
            if (mailMessageID.HasValue)
            {
                mailMessageIDParameter = new ObjectParameter("MailMessageID", mailMessageID);
            }
            else
            {
                mailMessageIDParameter = new ObjectParameter("MailMessageID", typeof(int));
            }
            return base.ExecuteFunction("usp_DeleteMailMessage", mailMessageIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mailAccountID">No Metadata Documentation available.</param>
        /// <param name="mailFolderTypeID">No Metadata Documentation available.</param>
        public virtual int usp_PurgeFolder(Nullable<int> mailAccountID, Nullable<short> mailFolderTypeID)
        {
    
            ObjectParameter mailAccountIDParameter;
    
            if (mailAccountID.HasValue)
            {
                mailAccountIDParameter = new ObjectParameter("MailAccountID", mailAccountID);
            }
            else
            {
                mailAccountIDParameter = new ObjectParameter("MailAccountID", typeof(int));
            }
    
            ObjectParameter mailFolderTypeIDParameter;
    
            if (mailFolderTypeID.HasValue)
            {
                mailFolderTypeIDParameter = new ObjectParameter("MailFolderTypeID", mailFolderTypeID);
            }
            else
            {
                mailFolderTypeIDParameter = new ObjectParameter("MailFolderTypeID", typeof(short));
            }
            return base.ExecuteFunction("usp_PurgeFolder", mailAccountIDParameter, mailFolderTypeIDParameter);
        }

        #endregion
    }
}
