//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miche.Orders.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAdjustmentOrderLineModification
    {
        public int OrderAdjustmentOrderLineModificationID { get; set; }
        public int OrderItemID { get; set; }
        public int OrderAdjustmentID { get; set; }
        public string PropertyName { get; set; }
        public int ModificationOperationID { get; set; }
        public Nullable<decimal> ModificationDecimalValue { get; set; }
        public string ModificationDescription { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
    }
}
