//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Miche.Orders.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public OrderItem()
        {
            this.OrderItemPrices = new HashSet<OrderItemPrice>();
            this.OrderAdjustmentOrderLineModifications = new HashSet<OrderAdjustmentOrderLineModification>();
        }
    
        public int OrderItemID { get; set; }
        public int OrderCustomerID { get; set; }
        public short OrderItemTypeID { get; set; }
        public Nullable<int> HostessRewardRuleID { get; set; }
        public Nullable<int> ParentOrderItemID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> ProductPriceTypeID { get; set; }
        public string ProductName { get; set; }
        public string SKU { get; set; }
        public Nullable<int> CatalogID { get; set; }
        public int Quantity { get; set; }
        public decimal ItemPrice { get; set; }
        public Nullable<decimal> ShippingTotal { get; set; }
        public Nullable<decimal> ShippingTotalOverride { get; set; }
        public Nullable<decimal> HandlingTotal { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<decimal> AdjustedPrice { get; set; }
        public Nullable<decimal> CommissionableTotal { get; set; }
        public Nullable<decimal> CommissionableTotalOverride { get; set; }
        public bool ChargeTax { get; set; }
        public bool ChargeShipping { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<decimal> MinCustomerSubtotal { get; set; }
        public Nullable<decimal> MaxCustomerSubtotal { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> TaxPercentCity { get; set; }
        public Nullable<decimal> TaxAmountCity { get; set; }
        public Nullable<decimal> TaxAmountCityLocal { get; set; }
        public Nullable<decimal> TaxPercentState { get; set; }
        public Nullable<decimal> TaxAmountState { get; set; }
        public Nullable<decimal> TaxPercentCounty { get; set; }
        public Nullable<decimal> TaxAmountCounty { get; set; }
        public Nullable<decimal> TaxAmountCountyLocal { get; set; }
        public Nullable<decimal> TaxPercentDistrict { get; set; }
        public Nullable<decimal> TaxAmountDistrict { get; set; }
        public Nullable<decimal> TaxPercentCountry { get; set; }
        public Nullable<decimal> TaxAmountCountry { get; set; }
        public Nullable<decimal> TaxableTotal { get; set; }
        public byte[] DataVersion { get; set; }
        public Nullable<int> ModifiedByUserID { get; set; }
        public Nullable<int> DynamicKitGroupID { get; set; }
        public Nullable<short> OrderItemParentTypeID { get; set; }
        public Nullable<decimal> ItemPriceActual { get; set; }
        public string TaxNumber { get; set; }
    
        public virtual OrderCustomer OrderCustomer { get; set; }
        public virtual ICollection<OrderItemPrice> OrderItemPrices { get; set; }
        public virtual ICollection<OrderAdjustmentOrderLineModification> OrderAdjustmentOrderLineModifications { get; set; }
    }
}
