//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelKade.Orders.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCustomer
    {
        public OrderCustomer()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int OrderCustomerID { get; set; }
        public short OrderCustomerTypeID { get; set; }
        public int OrderID { get; set; }
        public int AccountID { get; set; }
        public Nullable<decimal> ShippingTotal { get; set; }
        public Nullable<decimal> HandlingTotal { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> PaymentTotal { get; set; }
        public Nullable<decimal> CommissionableTotal { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.DateTime> FutureBookingDateUTC { get; set; }
        public Nullable<bool> IsTaxExempt { get; set; }
        public Nullable<decimal> TaxAmountTotal { get; set; }
        public Nullable<decimal> TaxAmountCity { get; set; }
        public Nullable<decimal> TaxAmountState { get; set; }
        public Nullable<decimal> TaxAmountCounty { get; set; }
        public Nullable<decimal> TaxAmountDistrict { get; set; }
        public Nullable<decimal> TaxAmountOrderItems { get; set; }
        public Nullable<decimal> TaxAmountShipping { get; set; }
        public Nullable<decimal> TaxableTotal { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public byte[] DataVersion { get; set; }
        public Nullable<int> ModifiedByUserID { get; set; }
        public Nullable<decimal> TaxAmountCountry { get; set; }
        public Nullable<int> ImportOrderID { get; set; }
        public Nullable<int> ImportRefundOrderID { get; set; }
        public bool IsBookingCredit { get; set; }
        public string TaxGeocode { get; set; }
        public string SalesTaxTransactionNumber { get; set; }
        public string UseTaxTransactionNumber { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}
