
exec dba_SmartTruncateTable MailMessageAttachments
exec dba_SmartTruncateTable MailAttachments
exec dba_SmartTruncateTable MailMessageGroupAddresses
exec dba_SmartTruncateTable MailMessageGroupStatusAudit
exec dba_SmartTruncateTable MailMessageGroups
exec dba_SmartTruncateTable MailMessages
