DELETE FROM RoleFunctions
--DBCC CHECKIDENT ('RoleFunctions', RESEED, 0)
DELETE FROM Functions
DBCC CHECKIDENT ('Functions', RESEED, 0)

INSERT INTO Functions (Title, [Enabled]) VALUES ('Sites', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Sites-Create and Edit Base Site', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Sites-Replicated Sites', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Sites-Site Pages', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Sites-Site Map', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Sites-News', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Sites-Calendar Events', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Sites-Resource Library', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Sites-PWS Content Review', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Sites-Term Translations', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Accounts', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Accounts-Notes', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Accounts-Create and Edit Account', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Accounts-Site Subscriptions', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Accounts-Billing and Shipping Profiles', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Accounts-Ledger', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Accounts-Add Ledger Entry', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Accounts-Disbursement Profiles', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Accounts-Autoship Template', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Orders', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Orders-Order Entry', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Orders-Return Order', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Orders-Override Order', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Admin', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Admin-Create and Edit User', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Admin-Create and Edit Role', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Admin-Create and Edit List Value', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Admin-Create and Edit Schedule', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Commissions', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Commissions-Run Commissions', 1)
INSERT INTO Functions (Title, [Enabled]) VALUES ('Commissions-Publish Commissions', 1)

INSERT INTO RoleFunctions (RoleID, FunctionID)
	SELECT 4, FunctionID FROM Functions