//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace HttpRedirectModule.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class MicheCoreEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new MicheCoreEntities object using the connection string found in the 'MicheCoreEntities' section of the application configuration file.
        /// </summary>
        public MicheCoreEntities() : base("name=MicheCoreEntities", "MicheCoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MicheCoreEntities object.
        /// </summary>
        public MicheCoreEntities(string connectionString) : base(connectionString, "MicheCoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new MicheCoreEntities object.
        /// </summary>
        public MicheCoreEntities(EntityConnection connection) : base(connection, "MicheCoreEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SiteUrl> SiteUrls
        {
            get
            {
                if ((_SiteUrls == null))
                {
                    _SiteUrls = base.CreateObjectSet<SiteUrl>("SiteUrls");
                }
                return _SiteUrls;
            }
        }
        private ObjectSet<SiteUrl> _SiteUrls;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RedirectMappingData> RedirectMappingDatas
        {
            get
            {
                if ((_RedirectMappingDatas == null))
                {
                    _RedirectMappingDatas = base.CreateObjectSet<RedirectMappingData>("RedirectMappingDatas");
                }
                return _RedirectMappingDatas;
            }
        }
        private ObjectSet<RedirectMappingData> _RedirectMappingDatas;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SiteUrls EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSiteUrls(SiteUrl siteUrl)
        {
            base.AddObject("SiteUrls", siteUrl);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RedirectMappingDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRedirectMappingDatas(RedirectMappingData redirectMappingData)
        {
            base.AddObject("RedirectMappingDatas", redirectMappingData);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MicheCoreModel", Name="RedirectMappingData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RedirectMappingData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RedirectMappingData object.
        /// </summary>
        /// <param name="mappingRedirectID">Initial value of the MappingRedirectID property.</param>
        public static RedirectMappingData CreateRedirectMappingData(global::System.Int32 mappingRedirectID)
        {
            RedirectMappingData redirectMappingData = new RedirectMappingData();
            redirectMappingData.MappingRedirectID = mappingRedirectID;
            return redirectMappingData;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MappingRedirectID
        {
            get
            {
                return _MappingRedirectID;
            }
            set
            {
                if (_MappingRedirectID != value)
                {
                    OnMappingRedirectIDChanging(value);
                    ReportPropertyChanging("MappingRedirectID");
                    _MappingRedirectID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MappingRedirectID");
                    OnMappingRedirectIDChanged();
                }
            }
        }
        private global::System.Int32 _MappingRedirectID;
        partial void OnMappingRedirectIDChanging(global::System.Int32 value);
        partial void OnMappingRedirectIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AccountID
        {
            get
            {
                return _AccountID;
            }
            set
            {
                OnAccountIDChanging(value);
                ReportPropertyChanging("AccountID");
                _AccountID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AccountID");
                OnAccountIDChanged();
            }
        }
        private Nullable<global::System.Int32> _AccountID;
        partial void OnAccountIDChanging(Nullable<global::System.Int32> value);
        partial void OnAccountIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SponsorID
        {
            get
            {
                return _SponsorID;
            }
            set
            {
                OnSponsorIDChanging(value);
                ReportPropertyChanging("SponsorID");
                _SponsorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SponsorID");
                OnSponsorIDChanged();
            }
        }
        private Nullable<global::System.Int32> _SponsorID;
        partial void OnSponsorIDChanging(Nullable<global::System.Int32> value);
        partial void OnSponsorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AccountNumber
        {
            get
            {
                return _AccountNumber;
            }
            set
            {
                OnAccountNumberChanging(value);
                ReportPropertyChanging("AccountNumber");
                _AccountNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AccountNumber");
                OnAccountNumberChanged();
            }
        }
        private global::System.String _AccountNumber;
        partial void OnAccountNumberChanging(global::System.String value);
        partial void OnAccountNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OldWebsiteName
        {
            get
            {
                return _OldWebsiteName;
            }
            set
            {
                OnOldWebsiteNameChanging(value);
                ReportPropertyChanging("OldWebsiteName");
                _OldWebsiteName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OldWebsiteName");
                OnOldWebsiteNameChanged();
            }
        }
        private global::System.String _OldWebsiteName;
        partial void OnOldWebsiteNameChanging(global::System.String value);
        partial void OnOldWebsiteNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SiteID
        {
            get
            {
                return _SiteID;
            }
            set
            {
                OnSiteIDChanging(value);
                ReportPropertyChanging("SiteID");
                _SiteID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SiteID");
                OnSiteIDChanged();
            }
        }
        private Nullable<global::System.Int32> _SiteID;
        partial void OnSiteIDChanging(Nullable<global::System.Int32> value);
        partial void OnSiteIDChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="MicheCoreModel", Name="SiteUrl")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SiteUrl : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SiteUrl object.
        /// </summary>
        /// <param name="siteUrlID">Initial value of the SiteUrlID property.</param>
        /// <param name="isPrimaryUrl">Initial value of the IsPrimaryUrl property.</param>
        public static SiteUrl CreateSiteUrl(global::System.Int32 siteUrlID, global::System.Boolean isPrimaryUrl)
        {
            SiteUrl siteUrl = new SiteUrl();
            siteUrl.SiteUrlID = siteUrlID;
            siteUrl.IsPrimaryUrl = isPrimaryUrl;
            return siteUrl;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SiteUrlID
        {
            get
            {
                return _SiteUrlID;
            }
            set
            {
                if (_SiteUrlID != value)
                {
                    OnSiteUrlIDChanging(value);
                    ReportPropertyChanging("SiteUrlID");
                    _SiteUrlID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SiteUrlID");
                    OnSiteUrlIDChanged();
                }
            }
        }
        private global::System.Int32 _SiteUrlID;
        partial void OnSiteUrlIDChanging(global::System.Int32 value);
        partial void OnSiteUrlIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SiteID
        {
            get
            {
                return _SiteID;
            }
            set
            {
                OnSiteIDChanging(value);
                ReportPropertyChanging("SiteID");
                _SiteID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SiteID");
                OnSiteIDChanged();
            }
        }
        private Nullable<global::System.Int32> _SiteID;
        partial void OnSiteIDChanging(Nullable<global::System.Int32> value);
        partial void OnSiteIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ExpirationDateUTC
        {
            get
            {
                return _ExpirationDateUTC;
            }
            set
            {
                OnExpirationDateUTCChanging(value);
                ReportPropertyChanging("ExpirationDateUTC");
                _ExpirationDateUTC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpirationDateUTC");
                OnExpirationDateUTCChanged();
            }
        }
        private Nullable<global::System.DateTime> _ExpirationDateUTC;
        partial void OnExpirationDateUTCChanging(Nullable<global::System.DateTime> value);
        partial void OnExpirationDateUTCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsPrimaryUrl
        {
            get
            {
                return _IsPrimaryUrl;
            }
            set
            {
                OnIsPrimaryUrlChanging(value);
                ReportPropertyChanging("IsPrimaryUrl");
                _IsPrimaryUrl = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPrimaryUrl");
                OnIsPrimaryUrlChanged();
            }
        }
        private global::System.Boolean _IsPrimaryUrl;
        partial void OnIsPrimaryUrlChanging(global::System.Boolean value);
        partial void OnIsPrimaryUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LanguageID
        {
            get
            {
                return _LanguageID;
            }
            set
            {
                OnLanguageIDChanging(value);
                ReportPropertyChanging("LanguageID");
                _LanguageID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LanguageID");
                OnLanguageIDChanged();
            }
        }
        private Nullable<global::System.Int32> _LanguageID;
        partial void OnLanguageIDChanging(Nullable<global::System.Int32> value);
        partial void OnLanguageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModifiedByUserID
        {
            get
            {
                return _ModifiedByUserID;
            }
            set
            {
                OnModifiedByUserIDChanging(value);
                ReportPropertyChanging("ModifiedByUserID");
                _ModifiedByUserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModifiedByUserID");
                OnModifiedByUserIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ModifiedByUserID;
        partial void OnModifiedByUserIDChanging(Nullable<global::System.Int32> value);
        partial void OnModifiedByUserIDChanged();

        #endregion
    
    }

    #endregion
    
}
