//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("EncorePromotionsModel", "FK_PromotionOrderAdjustment_OrderAdjustments", "Promotion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NetSteps.Promotions.Service.EntityModels.Promotion), "PromotionOrderAdjustment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NetSteps.Promotions.Service.EntityModels.PromotionOrderAdjustment), true)]
[assembly: EdmRelationshipAttribute("EncorePromotionsModel", "FK_PromotionQualification_Promotion", "Promotion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NetSteps.Promotions.Service.EntityModels.Promotion), "PromotionQualification", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NetSteps.Promotions.Service.EntityModels.PromotionQualification), true)]
[assembly: EdmRelationshipAttribute("EncorePromotionsModel", "FK_Successor", "Promotion", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(NetSteps.Promotions.Service.EntityModels.Promotion), "Promotion1", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NetSteps.Promotions.Service.EntityModels.Promotion), true)]
[assembly: EdmRelationshipAttribute("EncorePromotionsModel", "FK_PromotionRewardEffects_PromotionRewards", "PromotionReward", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NetSteps.Promotions.Service.EntityModels.PromotionReward), "PromotionRewardEffect", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NetSteps.Promotions.Service.EntityModels.PromotionRewardEffect), true)]
[assembly: EdmRelationshipAttribute("EncorePromotionsModel", "FK_PromotionReward_Promotion", "Promotion", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(NetSteps.Promotions.Service.EntityModels.Promotion), "PromotionReward", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(NetSteps.Promotions.Service.EntityModels.PromotionReward), true)]

#endregion

namespace NetSteps.Promotions.Service.EntityModels
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class NetStepsPromotionsEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializar un nuevo objeto NetStepsPromotionsEntities.
        /// </summary>
        public NetStepsPromotionsEntities(string connectionString) : base(connectionString, "NetStepsPromotionsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto NetStepsPromotionsEntities.
        /// </summary>
        public NetStepsPromotionsEntities(EntityConnection connection) : base(connection, "NetStepsPromotionsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<PromotionOrderAdjustment> PromotionOrderAdjustments
        {
            get
            {
                if ((_PromotionOrderAdjustments == null))
                {
                    _PromotionOrderAdjustments = base.CreateObjectSet<PromotionOrderAdjustment>("PromotionOrderAdjustments");
                }
                return _PromotionOrderAdjustments;
            }
        }
        private ObjectSet<PromotionOrderAdjustment> _PromotionOrderAdjustments;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<PromotionQualification> PromotionQualifications
        {
            get
            {
                if ((_PromotionQualifications == null))
                {
                    _PromotionQualifications = base.CreateObjectSet<PromotionQualification>("PromotionQualifications");
                }
                return _PromotionQualifications;
            }
        }
        private ObjectSet<PromotionQualification> _PromotionQualifications;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Promotion> Promotions
        {
            get
            {
                if ((_Promotions == null))
                {
                    _Promotions = base.CreateObjectSet<Promotion>("Promotions");
                }
                return _Promotions;
            }
        }
        private ObjectSet<Promotion> _Promotions;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<PromotionRewardEffect> PromotionRewardEffects
        {
            get
            {
                if ((_PromotionRewardEffects == null))
                {
                    _PromotionRewardEffects = base.CreateObjectSet<PromotionRewardEffect>("PromotionRewardEffects");
                }
                return _PromotionRewardEffects;
            }
        }
        private ObjectSet<PromotionRewardEffect> _PromotionRewardEffects;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<PromotionReward> PromotionRewards
        {
            get
            {
                if ((_PromotionRewards == null))
                {
                    _PromotionRewards = base.CreateObjectSet<PromotionReward>("PromotionRewards");
                }
                return _PromotionRewards;
            }
        }
        private ObjectSet<PromotionReward> _PromotionRewards;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet PromotionOrderAdjustments. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPromotionOrderAdjustments(PromotionOrderAdjustment promotionOrderAdjustment)
        {
            base.AddObject("PromotionOrderAdjustments", promotionOrderAdjustment);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet PromotionQualifications. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPromotionQualifications(PromotionQualification promotionQualification)
        {
            base.AddObject("PromotionQualifications", promotionQualification);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Promotions. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPromotions(Promotion promotion)
        {
            base.AddObject("Promotions", promotion);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet PromotionRewardEffects. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPromotionRewardEffects(PromotionRewardEffect promotionRewardEffect)
        {
            base.AddObject("PromotionRewardEffects", promotionRewardEffect);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet PromotionRewards. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPromotionRewards(PromotionReward promotionReward)
        {
            base.AddObject("PromotionRewards", promotionReward);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EncorePromotionsModel", Name="Promotion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Promotion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Promotion.
        /// </summary>
        /// <param name="promotionID">Valor inicial de la propiedad PromotionID.</param>
        /// <param name="description">Valor inicial de la propiedad Description.</param>
        /// <param name="promotionStatusTypeID">Valor inicial de la propiedad PromotionStatusTypeID.</param>
        public static Promotion CreatePromotion(global::System.Int32 promotionID, global::System.String description, global::System.Int32 promotionStatusTypeID)
        {
            Promotion promotion = new Promotion();
            promotion.PromotionID = promotionID;
            promotion.Description = description;
            promotion.PromotionStatusTypeID = promotionStatusTypeID;
            return promotion;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PromotionID
        {
            get
            {
                return _PromotionID;
            }
            set
            {
                if (_PromotionID != value)
                {
                    OnPromotionIDChanging(value);
                    ReportPropertyChanging("PromotionID");
                    _PromotionID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PromotionID");
                    OnPromotionIDChanged();
                }
            }
        }
        private global::System.Int32 _PromotionID;
        partial void OnPromotionIDChanging(global::System.Int32 value);
        partial void OnPromotionIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartDate
        {
            get
            {
                return _StartDate;
            }
            set
            {
                OnStartDateChanging(value);
                ReportPropertyChanging("StartDate");
                _StartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDate");
                OnStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartDate;
        partial void OnStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnStartDateChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndDate
        {
            get
            {
                return _EndDate;
            }
            set
            {
                OnEndDateChanging(value);
                ReportPropertyChanging("EndDate");
                _EndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndDate");
                OnEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndDate;
        partial void OnEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnEndDateChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PromotionStatusTypeID
        {
            get
            {
                return _PromotionStatusTypeID;
            }
            set
            {
                OnPromotionStatusTypeIDChanging(value);
                ReportPropertyChanging("PromotionStatusTypeID");
                _PromotionStatusTypeID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PromotionStatusTypeID");
                OnPromotionStatusTypeIDChanged();
            }
        }
        private global::System.Int32 _PromotionStatusTypeID;
        partial void OnPromotionStatusTypeIDChanging(global::System.Int32 value);
        partial void OnPromotionStatusTypeIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SuccessorPromotionID
        {
            get
            {
                return _SuccessorPromotionID;
            }
            set
            {
                OnSuccessorPromotionIDChanging(value);
                ReportPropertyChanging("SuccessorPromotionID");
                _SuccessorPromotionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SuccessorPromotionID");
                OnSuccessorPromotionIDChanged();
            }
        }
        private Nullable<global::System.Int32> _SuccessorPromotionID;
        partial void OnSuccessorPromotionIDChanging(Nullable<global::System.Int32> value);
        partial void OnSuccessorPromotionIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PromotionKind
        {
            get
            {
                return _PromotionKind;
            }
            set
            {
                OnPromotionKindChanging(value);
                ReportPropertyChanging("PromotionKind");
                _PromotionKind = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PromotionKind");
                OnPromotionKindChanged();
            }
        }
        private global::System.String _PromotionKind;
        partial void OnPromotionKindChanging(global::System.String value);
        partial void OnPromotionKindChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncorePromotionsModel", "FK_PromotionOrderAdjustment_OrderAdjustments", "PromotionOrderAdjustment")]
        public EntityCollection<PromotionOrderAdjustment> PromotionOrderAdjustments
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PromotionOrderAdjustment>("EncorePromotionsModel.FK_PromotionOrderAdjustment_OrderAdjustments", "PromotionOrderAdjustment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PromotionOrderAdjustment>("EncorePromotionsModel.FK_PromotionOrderAdjustment_OrderAdjustments", "PromotionOrderAdjustment", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncorePromotionsModel", "FK_PromotionQualification_Promotion", "PromotionQualification")]
        public EntityCollection<PromotionQualification> PromotionQualifications
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PromotionQualification>("EncorePromotionsModel.FK_PromotionQualification_Promotion", "PromotionQualification");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PromotionQualification>("EncorePromotionsModel.FK_PromotionQualification_Promotion", "PromotionQualification", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncorePromotionsModel", "FK_Successor", "Promotion1")]
        public EntityCollection<Promotion> Promotions1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Promotion>("EncorePromotionsModel.FK_Successor", "Promotion1");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Promotion>("EncorePromotionsModel.FK_Successor", "Promotion1", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncorePromotionsModel", "FK_Successor", "Promotion")]
        public Promotion Promotion1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Promotion>("EncorePromotionsModel.FK_Successor", "Promotion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Promotion>("EncorePromotionsModel.FK_Successor", "Promotion").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Promotion> Promotion1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Promotion>("EncorePromotionsModel.FK_Successor", "Promotion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Promotion>("EncorePromotionsModel.FK_Successor", "Promotion", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncorePromotionsModel", "FK_PromotionReward_Promotion", "PromotionReward")]
        public EntityCollection<PromotionReward> PromotionRewards
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PromotionReward>("EncorePromotionsModel.FK_PromotionReward_Promotion", "PromotionReward");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PromotionReward>("EncorePromotionsModel.FK_PromotionReward_Promotion", "PromotionReward", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EncorePromotionsModel", Name="PromotionOrderAdjustment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PromotionOrderAdjustment : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PromotionOrderAdjustment.
        /// </summary>
        /// <param name="orderAdjustmentID">Valor inicial de la propiedad OrderAdjustmentID.</param>
        /// <param name="promotionID">Valor inicial de la propiedad PromotionID.</param>
        public static PromotionOrderAdjustment CreatePromotionOrderAdjustment(global::System.Int32 orderAdjustmentID, global::System.Int32 promotionID)
        {
            PromotionOrderAdjustment promotionOrderAdjustment = new PromotionOrderAdjustment();
            promotionOrderAdjustment.OrderAdjustmentID = orderAdjustmentID;
            promotionOrderAdjustment.PromotionID = promotionID;
            return promotionOrderAdjustment;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OrderAdjustmentID
        {
            get
            {
                return _OrderAdjustmentID;
            }
            set
            {
                if (_OrderAdjustmentID != value)
                {
                    OnOrderAdjustmentIDChanging(value);
                    ReportPropertyChanging("OrderAdjustmentID");
                    _OrderAdjustmentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OrderAdjustmentID");
                    OnOrderAdjustmentIDChanged();
                }
            }
        }
        private global::System.Int32 _OrderAdjustmentID;
        partial void OnOrderAdjustmentIDChanging(global::System.Int32 value);
        partial void OnOrderAdjustmentIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PromotionID
        {
            get
            {
                return _PromotionID;
            }
            set
            {
                OnPromotionIDChanging(value);
                ReportPropertyChanging("PromotionID");
                _PromotionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PromotionID");
                OnPromotionIDChanged();
            }
        }
        private global::System.Int32 _PromotionID;
        partial void OnPromotionIDChanging(global::System.Int32 value);
        partial void OnPromotionIDChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncorePromotionsModel", "FK_PromotionOrderAdjustment_OrderAdjustments", "Promotion")]
        public Promotion Promotion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Promotion>("EncorePromotionsModel.FK_PromotionOrderAdjustment_OrderAdjustments", "Promotion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Promotion>("EncorePromotionsModel.FK_PromotionOrderAdjustment_OrderAdjustments", "Promotion").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Promotion> PromotionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Promotion>("EncorePromotionsModel.FK_PromotionOrderAdjustment_OrderAdjustments", "Promotion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Promotion>("EncorePromotionsModel.FK_PromotionOrderAdjustment_OrderAdjustments", "Promotion", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EncorePromotionsModel", Name="PromotionQualification")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PromotionQualification : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PromotionQualification.
        /// </summary>
        /// <param name="promotionQualificationID">Valor inicial de la propiedad PromotionQualificationID.</param>
        /// <param name="promotionID">Valor inicial de la propiedad PromotionID.</param>
        /// <param name="extensionProviderKey">Valor inicial de la propiedad ExtensionProviderKey.</param>
        public static PromotionQualification CreatePromotionQualification(global::System.Int32 promotionQualificationID, global::System.Int32 promotionID, global::System.String extensionProviderKey)
        {
            PromotionQualification promotionQualification = new PromotionQualification();
            promotionQualification.PromotionQualificationID = promotionQualificationID;
            promotionQualification.PromotionID = promotionID;
            promotionQualification.ExtensionProviderKey = extensionProviderKey;
            return promotionQualification;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PromotionQualificationID
        {
            get
            {
                return _PromotionQualificationID;
            }
            set
            {
                if (_PromotionQualificationID != value)
                {
                    OnPromotionQualificationIDChanging(value);
                    ReportPropertyChanging("PromotionQualificationID");
                    _PromotionQualificationID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PromotionQualificationID");
                    OnPromotionQualificationIDChanged();
                }
            }
        }
        private global::System.Int32 _PromotionQualificationID;
        partial void OnPromotionQualificationIDChanging(global::System.Int32 value);
        partial void OnPromotionQualificationIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PromotionID
        {
            get
            {
                return _PromotionID;
            }
            set
            {
                OnPromotionIDChanging(value);
                ReportPropertyChanging("PromotionID");
                _PromotionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PromotionID");
                OnPromotionIDChanged();
            }
        }
        private global::System.Int32 _PromotionID;
        partial void OnPromotionIDChanging(global::System.Int32 value);
        partial void OnPromotionIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ExtensionProviderKey
        {
            get
            {
                return _ExtensionProviderKey;
            }
            set
            {
                OnExtensionProviderKeyChanging(value);
                ReportPropertyChanging("ExtensionProviderKey");
                _ExtensionProviderKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ExtensionProviderKey");
                OnExtensionProviderKeyChanged();
            }
        }
        private global::System.String _ExtensionProviderKey;
        partial void OnExtensionProviderKeyChanging(global::System.String value);
        partial void OnExtensionProviderKeyChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PromotionPropertyKey
        {
            get
            {
                return _PromotionPropertyKey;
            }
            set
            {
                OnPromotionPropertyKeyChanging(value);
                ReportPropertyChanging("PromotionPropertyKey");
                _PromotionPropertyKey = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PromotionPropertyKey");
                OnPromotionPropertyKeyChanged();
            }
        }
        private global::System.String _PromotionPropertyKey;
        partial void OnPromotionPropertyKeyChanging(global::System.String value);
        partial void OnPromotionPropertyKeyChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncorePromotionsModel", "FK_PromotionQualification_Promotion", "Promotion")]
        public Promotion Promotion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Promotion>("EncorePromotionsModel.FK_PromotionQualification_Promotion", "Promotion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Promotion>("EncorePromotionsModel.FK_PromotionQualification_Promotion", "Promotion").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Promotion> PromotionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Promotion>("EncorePromotionsModel.FK_PromotionQualification_Promotion", "Promotion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Promotion>("EncorePromotionsModel.FK_PromotionQualification_Promotion", "Promotion", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EncorePromotionsModel", Name="PromotionReward")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PromotionReward : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PromotionReward.
        /// </summary>
        /// <param name="promotionRewardID">Valor inicial de la propiedad PromotionRewardID.</param>
        /// <param name="promotionID">Valor inicial de la propiedad PromotionID.</param>
        /// <param name="promotionRewardKind">Valor inicial de la propiedad PromotionRewardKind.</param>
        /// <param name="promotionPropertyKey">Valor inicial de la propiedad PromotionPropertyKey.</param>
        public static PromotionReward CreatePromotionReward(global::System.Int32 promotionRewardID, global::System.Int32 promotionID, global::System.String promotionRewardKind, global::System.String promotionPropertyKey)
        {
            PromotionReward promotionReward = new PromotionReward();
            promotionReward.PromotionRewardID = promotionRewardID;
            promotionReward.PromotionID = promotionID;
            promotionReward.PromotionRewardKind = promotionRewardKind;
            promotionReward.PromotionPropertyKey = promotionPropertyKey;
            return promotionReward;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PromotionRewardID
        {
            get
            {
                return _PromotionRewardID;
            }
            set
            {
                if (_PromotionRewardID != value)
                {
                    OnPromotionRewardIDChanging(value);
                    ReportPropertyChanging("PromotionRewardID");
                    _PromotionRewardID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PromotionRewardID");
                    OnPromotionRewardIDChanged();
                }
            }
        }
        private global::System.Int32 _PromotionRewardID;
        partial void OnPromotionRewardIDChanging(global::System.Int32 value);
        partial void OnPromotionRewardIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PromotionID
        {
            get
            {
                return _PromotionID;
            }
            set
            {
                OnPromotionIDChanging(value);
                ReportPropertyChanging("PromotionID");
                _PromotionID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PromotionID");
                OnPromotionIDChanged();
            }
        }
        private global::System.Int32 _PromotionID;
        partial void OnPromotionIDChanging(global::System.Int32 value);
        partial void OnPromotionIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PromotionRewardKind
        {
            get
            {
                return _PromotionRewardKind;
            }
            set
            {
                OnPromotionRewardKindChanging(value);
                ReportPropertyChanging("PromotionRewardKind");
                _PromotionRewardKind = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PromotionRewardKind");
                OnPromotionRewardKindChanged();
            }
        }
        private global::System.String _PromotionRewardKind;
        partial void OnPromotionRewardKindChanging(global::System.String value);
        partial void OnPromotionRewardKindChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PromotionPropertyKey
        {
            get
            {
                return _PromotionPropertyKey;
            }
            set
            {
                OnPromotionPropertyKeyChanging(value);
                ReportPropertyChanging("PromotionPropertyKey");
                _PromotionPropertyKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PromotionPropertyKey");
                OnPromotionPropertyKeyChanged();
            }
        }
        private global::System.String _PromotionPropertyKey;
        partial void OnPromotionPropertyKeyChanging(global::System.String value);
        partial void OnPromotionPropertyKeyChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncorePromotionsModel", "FK_PromotionRewardEffects_PromotionRewards", "PromotionRewardEffect")]
        public EntityCollection<PromotionRewardEffect> PromotionRewardEffects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PromotionRewardEffect>("EncorePromotionsModel.FK_PromotionRewardEffects_PromotionRewards", "PromotionRewardEffect");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PromotionRewardEffect>("EncorePromotionsModel.FK_PromotionRewardEffects_PromotionRewards", "PromotionRewardEffect", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncorePromotionsModel", "FK_PromotionReward_Promotion", "Promotion")]
        public Promotion Promotion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Promotion>("EncorePromotionsModel.FK_PromotionReward_Promotion", "Promotion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Promotion>("EncorePromotionsModel.FK_PromotionReward_Promotion", "Promotion").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Promotion> PromotionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Promotion>("EncorePromotionsModel.FK_PromotionReward_Promotion", "Promotion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Promotion>("EncorePromotionsModel.FK_PromotionReward_Promotion", "Promotion", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EncorePromotionsModel", Name="PromotionRewardEffect")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PromotionRewardEffect : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto PromotionRewardEffect.
        /// </summary>
        /// <param name="promotionRewardEffectID">Valor inicial de la propiedad PromotionRewardEffectID.</param>
        /// <param name="promotionRewardID">Valor inicial de la propiedad PromotionRewardID.</param>
        /// <param name="extensionProviderKey">Valor inicial de la propiedad ExtensionProviderKey.</param>
        /// <param name="rewardPropertyKey">Valor inicial de la propiedad RewardPropertyKey.</param>
        public static PromotionRewardEffect CreatePromotionRewardEffect(global::System.Int32 promotionRewardEffectID, global::System.Int32 promotionRewardID, global::System.String extensionProviderKey, global::System.String rewardPropertyKey)
        {
            PromotionRewardEffect promotionRewardEffect = new PromotionRewardEffect();
            promotionRewardEffect.PromotionRewardEffectID = promotionRewardEffectID;
            promotionRewardEffect.PromotionRewardID = promotionRewardID;
            promotionRewardEffect.ExtensionProviderKey = extensionProviderKey;
            promotionRewardEffect.RewardPropertyKey = rewardPropertyKey;
            return promotionRewardEffect;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PromotionRewardEffectID
        {
            get
            {
                return _PromotionRewardEffectID;
            }
            set
            {
                if (_PromotionRewardEffectID != value)
                {
                    OnPromotionRewardEffectIDChanging(value);
                    ReportPropertyChanging("PromotionRewardEffectID");
                    _PromotionRewardEffectID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PromotionRewardEffectID");
                    OnPromotionRewardEffectIDChanged();
                }
            }
        }
        private global::System.Int32 _PromotionRewardEffectID;
        partial void OnPromotionRewardEffectIDChanging(global::System.Int32 value);
        partial void OnPromotionRewardEffectIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PromotionRewardID
        {
            get
            {
                return _PromotionRewardID;
            }
            set
            {
                OnPromotionRewardIDChanging(value);
                ReportPropertyChanging("PromotionRewardID");
                _PromotionRewardID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PromotionRewardID");
                OnPromotionRewardIDChanged();
            }
        }
        private global::System.Int32 _PromotionRewardID;
        partial void OnPromotionRewardIDChanging(global::System.Int32 value);
        partial void OnPromotionRewardIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ExtensionProviderKey
        {
            get
            {
                return _ExtensionProviderKey;
            }
            set
            {
                OnExtensionProviderKeyChanging(value);
                ReportPropertyChanging("ExtensionProviderKey");
                _ExtensionProviderKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ExtensionProviderKey");
                OnExtensionProviderKeyChanged();
            }
        }
        private global::System.String _ExtensionProviderKey;
        partial void OnExtensionProviderKeyChanging(global::System.String value);
        partial void OnExtensionProviderKeyChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RewardPropertyKey
        {
            get
            {
                return _RewardPropertyKey;
            }
            set
            {
                OnRewardPropertyKeyChanging(value);
                ReportPropertyChanging("RewardPropertyKey");
                _RewardPropertyKey = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RewardPropertyKey");
                OnRewardPropertyKeyChanged();
            }
        }
        private global::System.String _RewardPropertyKey;
        partial void OnRewardPropertyKeyChanging(global::System.String value);
        partial void OnRewardPropertyKeyChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EncorePromotionsModel", "FK_PromotionRewardEffects_PromotionRewards", "PromotionReward")]
        public PromotionReward PromotionReward
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PromotionReward>("EncorePromotionsModel.FK_PromotionRewardEffects_PromotionRewards", "PromotionReward").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PromotionReward>("EncorePromotionsModel.FK_PromotionRewardEffects_PromotionRewards", "PromotionReward").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<PromotionReward> PromotionRewardReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<PromotionReward>("EncorePromotionsModel.FK_PromotionRewardEffects_PromotionRewards", "PromotionReward");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<PromotionReward>("EncorePromotionsModel.FK_PromotionRewardEffects_PromotionRewards", "PromotionReward", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
